rem #
rem #
rem #  ############################################################
rem #  ##                                                        ##
rem #  ##  compile.make  --  compile each of the TINKER modules  ##
rem #  ##                 (g95 for Linux Version)                ##
rem #  ##                                                        ##
rem #  ############################################################
rem #
rem #

mkdir o
cd o
gfortran -c -O -o action.o    ../../action.f
gfortran -c -O -o active.o    ../../active.f
gfortran -c -O -o alchemy.o   ../../alchemy.f
gfortran -c -O -o align.o     ../../align.f
gfortran -c -O -o analysis.o  ../../analysis.f
gfortran -c -O -o analyz.o    ../../analyz.f
gfortran -c -O -o analyze.o   ../../analyze.f
gfortran -c -O -o angang.o    ../../angang.f
gfortran -c -O -o angbnd.o    ../../angbnd.f
gfortran -c -O -o angles.o    ../../angles.f
gfortran -c -O -o angpot.o    ../../angpot.f
gfortran -c -O -o angtor.o    ../../angtor.f
gfortran -c -O -o anneal.o    ../../anneal.f
gfortran -c -O -o archive.o   ../../archive.f
gfortran -c -O -o argue.o     ../../argue.f
gfortran -c -O -o ascii.o     ../../ascii.f
gfortran -c -O -o atmlst.o    ../../atmlst.f
gfortran -c -O -o atomid.o    ../../atomid.f
gfortran -c -O -o atoms.o     ../../atoms.f
gfortran -c -O -o attach.o    ../../attach.f
gfortran -c -O -o bar.o       ../../bar.f
gfortran -c -O -o basefile.o  ../../basefile.f
gfortran -c -O -o bath.o      ../../bath.f
gfortran -c -O -o beeman.o    ../../beeman.f
gfortran -c -O -o bicubic.o   ../../bicubic.f
gfortran -c -O -o bitor.o     ../../bitor.f
gfortran -c -O -o bitors.o    ../../bitors.f
gfortran -c -O -o bndpot.o    ../../bndpot.f
gfortran -c -O -o bndstr.o    ../../bndstr.f
gfortran -c -O -o bonds.o     ../../bonds.f
gfortran -c -O -o born.o      ../../born.f
gfortran -c -O -o bound.o     ../../bound.f
gfortran -c -O -o bounds.o    ../../bounds.f
gfortran -c -O -o boxes.o     ../../boxes.f
gfortran -c -O -o bussi.o     ../../bussi.f
gfortran -c -O -o calendar.o  ../../calendar.f
gfortran -c -O -o cell.o      ../../cell.f
gfortran -c -O -o center.o    ../../center.f
gfortran -c -O -o charge.o    ../../charge.f
gfortran -c -O -o chgpot.o    ../../chgpot.f
gfortran -c -O -o chkpole.o   ../../chkpole.f
gfortran -c -O -o chkring.o   ../../chkring.f
gfortran -c -O -o chkxyz.o    ../../chkxyz.f
gfortran -c -O -o cholesky.o  ../../cholesky.f
gfortran -c -O -o chrono.o    ../../chrono.f
gfortran -c -O -o chunks.o    ../../chunks.f
gfortran -c -O -o clock.o     ../../clock.f
gfortran -c -O -o cluster.o   ../../cluster.f
gfortran -c -O -o column.o    ../../column.f
gfortran -c -O -o command.o   ../../command.f
gfortran -c -O -o connect.o   ../../connect.f
gfortran -c -O -o connolly.o  ../../connolly.f
gfortran -c -O -o control.o   ../../control.f
gfortran -c -O -o correlate.o ../../correlate.f
gfortran -c -O -o couple.o    ../../couple.f
gfortran -c -O -o crystal.o   ../../crystal.f
gfortran -c -O -o cspline.o   ../../cspline.f
gfortran -c -O -o cutoffs.o   ../../cutoffs.f
gfortran -c -O -o deflate.o   ../../deflate.f
gfortran -c -O -o delete.o    ../../delete.f
gfortran -c -O -o deriv.o     ../../deriv.f
gfortran -c -O -o diagq.o     ../../diagq.f
gfortran -c -O -o diffeq.o    ../../diffeq.f
gfortran -c -O -o diffuse.o   ../../diffuse.f
gfortran -c -O -o dipole.o    ../../dipole.f
gfortran -c -O -o disgeo.o    ../../disgeo.f
gfortran -c -O -o distgeom.o  ../../distgeom.f
gfortran -c -O -o dma.o       ../../dma.f
gfortran -c -O -o document.o  ../../document.f
gfortran -c -O -o domega.o    ../../domega.f
gfortran -c -O -o dynamic.o   ../../dynamic.f
gfortran -c -O -o eangang.o   ../../eangang.f
gfortran -c -O -o eangang1.o  ../../eangang1.f
gfortran -c -O -o eangang2.o  ../../eangang2.f
gfortran -c -O -o eangang3.o  ../../eangang3.f
gfortran -c -O -o eangle.o    ../../eangle.f
gfortran -c -O -o eangle1.o   ../../eangle1.f
gfortran -c -O -o eangle2.o   ../../eangle2.f
gfortran -c -O -o eangle3.o   ../../eangle3.f
gfortran -c -O -o eangtor.o   ../../eangtor.f
gfortran -c -O -o eangtor1.o  ../../eangtor1.f
gfortran -c -O -o eangtor2.o  ../../eangtor2.f
gfortran -c -O -o eangtor3.o  ../../eangtor3.f
gfortran -c -O -o ebond.o     ../../ebond.f
gfortran -c -O -o ebond1.o    ../../ebond1.f
gfortran -c -O -o ebond2.o    ../../ebond2.f
gfortran -c -O -o ebond3.o    ../../ebond3.f
gfortran -c -O -o ebuck.o     ../../ebuck.f
gfortran -c -O -o ebuck1.o    ../../ebuck1.f
gfortran -c -O -o ebuck2.o    ../../ebuck2.f
gfortran -c -O -o ebuck3.o    ../../ebuck3.f
gfortran -c -O -o echarge.o   ../../echarge.f
gfortran -c -O -o echarge1.o  ../../echarge1.f
gfortran -c -O -o echarge2.o  ../../echarge2.f
gfortran -c -O -o echarge3.o  ../../echarge3.f
gfortran -c -O -o echgdpl.o   ../../echgdpl.f
gfortran -c -O -o echgdpl1.o  ../../echgdpl1.f
gfortran -c -O -o echgdpl2.o  ../../echgdpl2.f
gfortran -c -O -o echgdpl3.o  ../../echgdpl3.f
gfortran -c -O -o edipole.o   ../../edipole.f
gfortran -c -O -o edipole1.o  ../../edipole1.f
gfortran -c -O -o edipole2.o  ../../edipole2.f
gfortran -c -O -o edipole3.o  ../../edipole3.f
gfortran -c -O -o egauss.o    ../../egauss.f
gfortran -c -O -o egauss1.o   ../../egauss1.f
gfortran -c -O -o egauss2.o   ../../egauss2.f
gfortran -c -O -o egauss3.o   ../../egauss3.f
gfortran -c -O -o egeom.o     ../../egeom.f
gfortran -c -O -o egeom1.o    ../../egeom1.f
gfortran -c -O -o egeom2.o    ../../egeom2.f
gfortran -c -O -o egeom3.o    ../../egeom3.f
gfortran -c -O -o ehal.o      ../../ehal.f
gfortran -c -O -o ehal1.o     ../../ehal1.f
gfortran -c -O -o ehal2.o     ../../ehal2.f
gfortran -c -O -o ehal3.o     ../../ehal3.f
gfortran -c -O -o eimprop.o   ../../eimprop.f
gfortran -c -O -o eimprop1.o  ../../eimprop1.f
gfortran -c -O -o eimprop2.o  ../../eimprop2.f
gfortran -c -O -o eimprop3.o  ../../eimprop3.f
gfortran -c -O -o eimptor.o   ../../eimptor.f
gfortran -c -O -o eimptor1.o  ../../eimptor1.f
gfortran -c -O -o eimptor2.o  ../../eimptor2.f
gfortran -c -O -o eimptor3.o  ../../eimptor3.f
gfortran -c -O -o elj.o       ../../elj.f
gfortran -c -O -o elj1.o      ../../elj1.f
gfortran -c -O -o elj2.o      ../../elj2.f
gfortran -c -O -o elj3.o      ../../elj3.f
gfortran -c -O -o embed.o     ../../embed.f
gfortran -c -O -o emetal.o    ../../emetal.f
gfortran -c -O -o emetal1.o   ../../emetal1.f
gfortran -c -O -o emetal2.o   ../../emetal2.f
gfortran -c -O -o emetal3.o   ../../emetal3.f
gfortran -c -O -o emm3hb.o    ../../emm3hb.f
gfortran -c -O -o emm3hb1.o   ../../emm3hb1.f
gfortran -c -O -o emm3hb2.o   ../../emm3hb2.f
gfortran -c -O -o emm3hb3.o   ../../emm3hb3.f
gfortran -c -O -o empole.o    ../../empole.f
gfortran -c -O -o empole1.o   ../../empole1.f
gfortran -c -O -o empole2.o   ../../empole2.f
gfortran -c -O -o empole3.o   ../../empole3.f
gfortran -c -O -o energi.o    ../../energi.f
gfortran -c -O -o energy.o    ../../energy.f
gfortran -c -O -o eopbend.o   ../../eopbend.f
gfortran -c -O -o eopbend1.o  ../../eopbend1.f
gfortran -c -O -o eopbend2.o  ../../eopbend2.f
gfortran -c -O -o eopbend3.o  ../../eopbend3.f
gfortran -c -O -o eopdist.o   ../../eopdist.f
gfortran -c -O -o eopdist1.o  ../../eopdist1.f
gfortran -c -O -o eopdist2.o  ../../eopdist2.f
gfortran -c -O -o eopdist3.o  ../../eopdist3.f
gfortran -c -O -o epitors.o   ../../epitors.f
gfortran -c -O -o epitors1.o  ../../epitors1.f
gfortran -c -O -o epitors2.o  ../../epitors2.f
gfortran -c -O -o epitors3.o  ../../epitors3.f
gfortran -c -O -o erf.o       ../../erf.f
gfortran -c -O -o erxnfld.o   ../../erxnfld.f
gfortran -c -O -o erxnfld1.o  ../../erxnfld1.f
gfortran -c -O -o erxnfld2.o  ../../erxnfld2.f
gfortran -c -O -o erxnfld3.o  ../../erxnfld3.f
gfortran -c -O -o esolv.o     ../../esolv.f
gfortran -c -O -o esolv1.o    ../../esolv1.f
gfortran -c -O -o esolv2.o    ../../esolv2.f
gfortran -c -O -o esolv3.o    ../../esolv3.f
gfortran -c -O -o estrbnd.o   ../../estrbnd.f
gfortran -c -O -o estrbnd1.o  ../../estrbnd1.f
gfortran -c -O -o estrbnd2.o  ../../estrbnd2.f
gfortran -c -O -o estrbnd3.o  ../../estrbnd3.f
gfortran -c -O -o estrtor.o   ../../estrtor.f
gfortran -c -O -o estrtor1.o  ../../estrtor1.f
gfortran -c -O -o estrtor2.o  ../../estrtor2.f
gfortran -c -O -o estrtor3.o  ../../estrtor3.f
gfortran -c -O -o etors.o     ../../etors.f
gfortran -c -O -o etors1.o    ../../etors1.f
gfortran -c -O -o etors2.o    ../../etors2.f
gfortran -c -O -o etors3.o    ../../etors3.f
gfortran -c -O -o etortor.o   ../../etortor.f
gfortran -c -O -o etortor1.o  ../../etortor1.f
gfortran -c -O -o etortor2.o  ../../etortor2.f
gfortran -c -O -o etortor3.o  ../../etortor3.f
gfortran -c -O -o eurey.o     ../../eurey.f
gfortran -c -O -o eurey1.o    ../../eurey1.f
gfortran -c -O -o eurey2.o    ../../eurey2.f
gfortran -c -O -o eurey3.o    ../../eurey3.f
gfortran -c -O -o evcorr.o    ../../evcorr.f
gfortran -c -O -o ewald.o     ../../ewald.f
gfortran -c -O -o extra.o     ../../extra.f
gfortran -c -O -o extra1.o    ../../extra1.f
gfortran -c -O -o extra2.o    ../../extra2.f
gfortran -c -O -o extra3.o    ../../extra3.f
gfortran -c -O -o faces.o     ../../faces.f
gfortran -c -O -o fatal.o     ../../fatal.f
gfortran -c -O -o fft.o       ../../fft.f
gfortran -c -O -o fft3d.o     ../../fft3d.f
gfortran -c -O -o fftpack.o   ../../fftpack.f
gfortran -c -O -o field.o     ../../field.f
gfortran -c -O -o fields.o    ../../fields.f
gfortran -c -O -o files.o     ../../files.f
gfortran -c -O -o final.o     ../../final.f
gfortran -c -O -o flatten.o   ../../flatten.f
gfortran -c -O -o fracs.o     ../../fracs.f
gfortran -c -O -o freeunit.o  ../../freeunit.f
gfortran -c -O -o freeze.o    ../../freeze.f
gfortran -c -O -o gda.o       ../../gda.f
gfortran -c -O -o geometry.o  ../../geometry.f
gfortran -c -O -o getint.o    ../../getint.f
gfortran -c -O -o getkey.o    ../../getkey.f
gfortran -c -O -o getmol.o    ../../getmol.f
gfortran -c -O -o getmol2.o   ../../getmol2.f
gfortran -c -O -o getnumb.o   ../../getnumb.f
gfortran -c -O -o getpdb.o    ../../getpdb.f
gfortran -c -O -o getprm.o    ../../getprm.f
gfortran -c -O -o getref.o    ../../getref.f
gfortran -c -O -o getstring.o ../../getstring.f
gfortran -c -O -o gettext.o   ../../gettext.f
gfortran -c -O -o getword.o   ../../getword.f
gfortran -c -O -o getxyz.o    ../../getxyz.f
gfortran -c -O -o ghmcstep.o  ../../ghmcstep.f
gfortran -c -O -o gkstuf.o    ../../gkstuf.f
gfortran -c -O -o gradient.o  ../../gradient.f
gfortran -c -O -o gradrgd.o   ../../gradrgd.f
gfortran -c -O -o gradrot.o   ../../gradrot.f
gfortran -c -O -o group.o     ../../group.f
gfortran -c -O -o groups.o    ../../groups.f
gfortran -c -O -o grpline.o   ../../grpline.f
gfortran -c -O -o gyrate.o    ../../gyrate.f
gfortran -c -O -o hescut.o    ../../hescut.f
gfortran -c -O -o hessian.o   ../../hessian.f
gfortran -c -O -o hessn.o     ../../hessn.f
gfortran -c -O -o hessrgd.o   ../../hessrgd.f
gfortran -c -O -o hessrot.o   ../../hessrot.f
gfortran -c -O -o hpmf.o      ../../hpmf.f
gfortran -c -O -o hybrid.o    ../../hybrid.f
gfortran -c -O -o image.o     ../../image.f
gfortran -c -O -o impose.o    ../../impose.f
gfortran -c -O -o improp.o    ../../improp.f
gfortran -c -O -o imptor.o    ../../imptor.f
gfortran -c -O -o induce.o    ../../induce.f
gfortran -c -O -o inertia.o   ../../inertia.f
gfortran -c -O -o inform.o    ../../inform.f
gfortran -c -O -o initatom.o  ../../initatom.f
gfortran -c -O -o initial.o   ../../initial.f
gfortran -c -O -o initprm.o   ../../initprm.f
gfortran -c -O -o initres.o   ../../initres.f
gfortran -c -O -o initrot.o   ../../initrot.f
gfortran -c -O -o insert.o    ../../insert.f
gfortran -c -O -o intedit.o   ../../intedit.f
gfortran -c -O -o inter.o     ../../inter.f
gfortran -c -O -o intxyz.o    ../../intxyz.f
gfortran -c -O -o invbeta.o   ../../invbeta.f
gfortran -c -O -o invert.o    ../../invert.f
gfortran -c -O -o iounit.o    ../../iounit.f
gfortran -c -O -o jacobi.o    ../../jacobi.f
gfortran -c -O -o kanang.o    ../../kanang.f
gfortran -c -O -o kangang.o   ../../kangang.f
gfortran -c -O -o kangle.o    ../../kangle.f
gfortran -c -O -o kangs.o     ../../kangs.f
gfortran -c -O -o kangtor.o   ../../kangtor.f
gfortran -c -O -o kantor.o    ../../kantor.f
gfortran -c -O -o katom.o     ../../katom.f
gfortran -c -O -o katoms.o    ../../katoms.f
gfortran -c -O -o kbond.o     ../../kbond.f
gfortran -c -O -o kbonds.o    ../../kbonds.f
gfortran -c -O -o kcharge.o   ../../kcharge.f
gfortran -c -O -o kchrge.o    ../../kchrge.f
gfortran -c -O -o kdipol.o    ../../kdipol.f
gfortran -c -O -o kdipole.o   ../../kdipole.f
gfortran -c -O -o kewald.o    ../../kewald.f
gfortran -c -O -o kextra.o    ../../kextra.f
gfortran -c -O -o keys.o      ../../keys.f
gfortran -c -O -o kgeom.o     ../../kgeom.f
gfortran -c -O -o khbond.o    ../../khbond.f
gfortran -c -O -o kimprop.o   ../../kimprop.f
gfortran -c -O -o kimptor.o   ../../kimptor.f
gfortran -c -O -o kinetic.o   ../../kinetic.f
gfortran -c -O -o kiprop.o    ../../kiprop.f
gfortran -c -O -o kitors.o    ../../kitors.f
gfortran -c -O -o kmetal.o    ../../kmetal.f
gfortran -c -O -o kmpole.o    ../../kmpole.f
gfortran -c -O -o kmulti.o    ../../kmulti.f
gfortran -c -O -o kopbend.o   ../../kopbend.f
gfortran -c -O -o kopbnd.o    ../../kopbnd.f
gfortran -c -O -o kopdist.o   ../../kopdist.f
gfortran -c -O -o kopdst.o    ../../kopdst.f
gfortran -c -O -o korbit.o    ../../korbit.f
gfortran -c -O -o korbs.o     ../../korbs.f
gfortran -c -O -o kpitor.o    ../../kpitor.f
gfortran -c -O -o kpitors.o   ../../kpitors.f
gfortran -c -O -o kpolar.o    ../../kpolar.f
gfortran -c -O -o kpolr.o     ../../kpolr.f
gfortran -c -O -o ksolv.o     ../../ksolv.f
gfortran -c -O -o kstbnd.o    ../../kstbnd.f
gfortran -c -O -o kstrbnd.o   ../../kstrbnd.f
gfortran -c -O -o kstrtor.o   ../../kstrtor.f
gfortran -c -O -o ksttor.o    ../../ksttor.f
gfortran -c -O -o ktors.o     ../../ktors.f
gfortran -c -O -o ktorsn.o    ../../ktorsn.f
gfortran -c -O -o ktortor.o   ../../ktortor.f
gfortran -c -O -o ktrtor.o    ../../ktrtor.f
gfortran -c -O -o kurey.o     ../../kurey.f
gfortran -c -O -o kurybr.o    ../../kurybr.f
gfortran -c -O -o kvdw.o      ../../kvdw.f
gfortran -c -O -o kvdwpr.o    ../../kvdwpr.f
gfortran -c -O -o kvdws.o     ../../kvdws.f
gfortran -c -O -o lattice.o   ../../lattice.f
gfortran -c -O -o lbfgs.o     ../../lbfgs.f
gfortran -c -O -o light.o     ../../light.f
gfortran -c -O -o lights.o    ../../lights.f
gfortran -c -O -o limits.o    ../../limits.f
gfortran -c -O -o linmin.o    ../../linmin.f
gfortran -c -O -o makeint.o   ../../makeint.f
gfortran -c -O -o makeref.o   ../../makeref.f
gfortran -c -O -o makexyz.o   ../../makexyz.f
gfortran -c -O -o math.o      ../../math.f
gfortran -c -O -o maxwell.o   ../../maxwell.f
gfortran -c -O -o mdinit.o    ../../mdinit.f
gfortran -c -O -o mdrest.o    ../../mdrest.f
gfortran -c -O -o mdsave.o    ../../mdsave.f
gfortran -c -O -o mdstat.o    ../../mdstat.f
gfortran -c -O -o mdstuf.o    ../../mdstuf.f
gfortran -c -O -o mechanic.o  ../../mechanic.f
gfortran -c -O -o merck.o     ../../merck.f
gfortran -c -O -o merge.o     ../../merge.f
gfortran -c -O -o minima.o    ../../minima.f
gfortran -c -O -o minimize.o  ../../minimize.f
gfortran -c -O -o minirot.o   ../../minirot.f
gfortran -c -O -o minrigid.o  ../../minrigid.f
gfortran -c -O -o molcul.o    ../../molcul.f
gfortran -c -O -o moldyn.o    ../../moldyn.f
gfortran -c -O -o molecule.o  ../../molecule.f
gfortran -c -O -o molxyz.o    ../../molxyz.f
gfortran -c -O -o moment.o    ../../moment.f
gfortran -c -O -o moments.o   ../../moments.f
gfortran -c -O -o monte.o     ../../monte.f
gfortran -c -O -o mplpot.o    ../../mplpot.f
gfortran -c -O -o mpole.o     ../../mpole.f
gfortran -c -O -o mutant.o    ../../mutant.f
gfortran -c -O -o mutate.o    ../../mutate.f
gfortran -c -O -o nblist.o    ../../nblist.f
gfortran -c -O -o neigh.o     ../../neigh.f
gfortran -c -O -o newton.o    ../../newton.f
gfortran -c -O -o newtrot.o   ../../newtrot.f
gfortran -c -O -o nextarg.o   ../../nextarg.f
gfortran -c -O -o nexttext.o  ../../nexttext.f
gfortran -c -O -o nonpol.o    ../../nonpol.f
gfortran -c -O -o nose.o      ../../nose.f
gfortran -c -O -o nspline.o   ../../nspline.f
gfortran -c -O -o nucleic.o   ../../nucleic.f
gfortran -c -O -o nucleo.o    ../../nucleo.f
gfortran -c -O -o number.o    ../../number.f
gfortran -c -O -o numeral.o   ../../numeral.f
gfortran -c -O -o numgrad.o   ../../numgrad.f
gfortran -c -O -o ocvm.o      ../../ocvm.f
gfortran -c -O -o omega.o     ../../omega.f
gfortran -c -O -o opbend.o    ../../opbend.f
gfortran -c -O -o opdist.o    ../../opdist.f
gfortran -c -O -o openend.o   ../../openend.f
gfortran -c -O -o openmp.o    ../../openmp.f
gfortran -c -O -o optimize.o  ../../optimize.f
gfortran -c -O -o optirot.o   ../../optirot.f
gfortran -c -O -o optrigid.o  ../../optrigid.f
gfortran -c -O -o optsave.o   ../../optsave.f
gfortran -c -O -o orbital.o   ../../orbital.f
gfortran -c -O -o orbits.o    ../../orbits.f
gfortran -c -O -o orient.o    ../../orient.f
gfortran -c -O -o orthog.o    ../../orthog.f
gfortran -c -O -o output.o    ../../output.f
gfortran -c -O -o overlap.o   ../../overlap.f
gfortran -c -O -o params.o    ../../params.f
gfortran -c -O -o path.o      ../../path.f
gfortran -c -O -o paths.o     ../../paths.f
gfortran -c -O -o pbstuf.o    ../../pbstuf.f
gfortran -c -O -o pdb.o       ../../pdb.f
gfortran -c -O -o pdbxyz.o    ../../pdbxyz.f
gfortran -c -O -o phipsi.o    ../../phipsi.f
gfortran -c -O -o picalc.o    ../../picalc.f
gfortran -c -O -o piorbs.o    ../../piorbs.f
gfortran -c -O -o pistuf.o    ../../pistuf.f
gfortran -c -O -o pitors.o    ../../pitors.f
gfortran -c -O -o pme.o       ../../pme.f
gfortran -c -O -o pmestuff.o  ../../pmestuff.f
gfortran -c -O -o pmpb.o      ../../pmpb.f
gfortran -c -O -o polar.o     ../../polar.f
gfortran -c -O -o polarize.o  ../../polarize.f
gfortran -c -O -o poledit.o   ../../poledit.f
gfortran -c -O -o polgrp.o    ../../polgrp.f
gfortran -c -O -o polpot.o    ../../polpot.f
gfortran -c -O -o polymer.o   ../../polymer.f
gfortran -c -O -o potent.o    ../../potent.f
gfortran -c -O -o potential.o ../../potential.f
gfortran -c -O -o potfit.o    ../../potfit.f
gfortran -c -O -o precis.o    ../../precis.f
gfortran -c -O -o precise.o   ../../precise.f
gfortran -c -O -o pressure.o  ../../pressure.f
gfortran -c -O -o prmedit.o   ../../prmedit.f
gfortran -c -O -o prmkey.o    ../../prmkey.f
gfortran -c -O -o promo.o     ../../promo.f
gfortran -c -O -o protein.o   ../../protein.f
gfortran -c -O -o prtdyn.o    ../../prtdyn.f
gfortran -c -O -o prterr.o    ../../prterr.f
gfortran -c -O -o prtint.o    ../../prtint.f
gfortran -c -O -o prtmol2.o   ../../prtmol2.f
gfortran -c -O -o prtpdb.o    ../../prtpdb.f
gfortran -c -O -o prtprm.o    ../../prtprm.f
gfortran -c -O -o prtseq.o    ../../prtseq.f
gfortran -c -O -o prtxyz.o    ../../prtxyz.f
gfortran -c -O -o pss.o       ../../pss.f
gfortran -c -O -o pssrigid.o  ../../pssrigid.f
gfortran -c -O -o pssrot.o    ../../pssrot.f
gfortran -c -O -o ptable.o    ../../ptable.f
gfortran -c -O -o qmstuf.o    ../../qmstuf.f
gfortran -c -O -o qrfact.o    ../../qrfact.f
gfortran -c -O -o quatfit.o   ../../quatfit.f
gfortran -c -O -o radial.o    ../../radial.f
gfortran -c -O -o random.o    ../../random.f
gfortran -c -O -o rattle.o    ../../rattle.f
gfortran -c -O -o readdyn.o   ../../readdyn.f
gfortran -c -O -o readgau.o   ../../readgau.f
gfortran -c -O -o readint.o   ../../readint.f
gfortran -c -O -o readmol.o   ../../readmol.f
gfortran -c -O -o readmol2.o  ../../readmol2.f
gfortran -c -O -o readpdb.o   ../../readpdb.f
gfortran -c -O -o readprm.o   ../../readprm.f
gfortran -c -O -o readseq.o   ../../readseq.f
gfortran -c -O -o readxyz.o   ../../readxyz.f
gfortran -c -O -o refer.o     ../../refer.f
gfortran -c -O -o replica.o   ../../replica.f
gfortran -c -O -o resdue.o    ../../resdue.f
gfortran -c -O -o respa.o     ../../respa.f
gfortran -c -O -o restrn.o    ../../restrn.f
gfortran -c -O -o rgddyn.o    ../../rgddyn.f
gfortran -c -O -o rgdstep.o   ../../rgdstep.f
gfortran -c -O -o rigid.o     ../../rigid.f
gfortran -c -O -o ring.o      ../../ring.f
gfortran -c -O -o rings.o     ../../rings.f
gfortran -c -O -o rmsfit.o    ../../rmsfit.f
gfortran -c -O -o rotbnd.o    ../../rotbnd.f
gfortran -c -O -o rotlist.o   ../../rotlist.f
gfortran -c -O -o rotpole.o   ../../rotpole.f
gfortran -c -O -o rxnfld.o    ../../rxnfld.f
gfortran -c -O -o rxnpot.o    ../../rxnpot.f
gfortran -c -O -o saddle.o    ../../saddle.f
gfortran -c -O -o scales.o    ../../scales.f
gfortran -c -O -o scan.o      ../../scan.f
gfortran -c -O -o sdstep.o    ../../sdstep.f
gfortran -c -O -o search.o    ../../search.f
gfortran -c -O -o sequen.o    ../../sequen.f
gfortran -c -O -o server.o    ../../server.f
gfortran -c -O -o shakeup.o   ../../shakeup.f
gfortran -c -O -o shunt.o     ../../shunt.f
gfortran -c -O -o sigmoid.o   ../../sigmoid.f
gfortran -c -O -o sizes.o     ../../sizes.f
gfortran -c -O -o sktstuff.o  ../../sktstuff.f
gfortran -c -O -o sniffer.o   ../../sniffer.f
gfortran -c -O -o socket.o    ../../socket.f
gfortran -c -O -o solute.o    ../../solute.f
gfortran -c -O -o sort.o      ../../sort.f
gfortran -c -O -o spacefill.o ../../spacefill.f
gfortran -c -O -o spectrum.o  ../../spectrum.f
gfortran -c -O -o square.o    ../../square.f
gfortran -c -O -o stodyn.o    ../../stodyn.f
gfortran -c -O -o strbnd.o    ../../strbnd.f
gfortran -c -O -o strtor.o    ../../strtor.f
gfortran -c -O -o suffix.o    ../../suffix.f
gfortran -c -O -o superpose.o ../../superpose.f
gfortran -c -O -o surface.o   ../../surface.f
gfortran -c -O -o surfatom.o  ../../surfatom.f
gfortran -c -O -o switch.o    ../../switch.f
gfortran -c -O -o sybylxyz.o  ../../sybylxyz.f
gfortran -c -O -o syntrn.o    ../../syntrn.f
gfortran -c -O -o tarray.o    ../../tarray.f
gfortran -c -O -o temper.o    ../../temper.f
gfortran -c -O -o testgrad.o  ../../testgrad.f
gfortran -c -O -o testhess.o  ../../testhess.f
gfortran -c -O -o testpair.o  ../../testpair.f
gfortran -c -O -o testpol.o   ../../testpol.f
gfortran -c -O -o testrot.o   ../../testrot.f
gfortran -c -O -o timer.o     ../../timer.f
gfortran -c -O -o timerot.o   ../../timerot.f
gfortran -c -O -o titles.o    ../../titles.f
gfortran -c -O -o tncg.o      ../../tncg.f
gfortran -c -O -o torphase.o  ../../torphase.f
gfortran -c -O -o torpot.o    ../../torpot.f
gfortran -c -O -o torque.o    ../../torque.f
gfortran -c -O -o tors.o      ../../tors.f
gfortran -c -O -o torsfit.o   ../../torsfit.f
gfortran -c -O -o torsions.o  ../../torsions.f
gfortran -c -O -o tortor.o    ../../tortor.f
gfortran -c -O -o tree.o      ../../tree.f
gfortran -c -O -o trimtext.o  ../../trimtext.f
gfortran -c -O -o unitcell.o  ../../unitcell.f
gfortran -c -O -o units.o     ../../units.f
gfortran -c -O -o uprior.o    ../../uprior.f
gfortran -c -O -o urey.o      ../../urey.f
gfortran -c -O -o urypot.o    ../../urypot.f
gfortran -c -O -o usage.o     ../../usage.f
gfortran -c -O -o usolve.o    ../../usolve.f
gfortran -c -O -o valence.o   ../../valence.f
gfortran -c -O -o valfit.o    ../../valfit.f
gfortran -c -O -o vdw.o       ../../vdw.f
gfortran -c -O -o vdwpot.o    ../../vdwpot.f
gfortran -c -O -o verlet.o    ../../verlet.f
gfortran -c -O -o version.o   ../../version.f
gfortran -c -O -o vibbig.o    ../../vibbig.f
gfortran -c -O -o vibrate.o   ../../vibrate.f
gfortran -c -O -o vibrot.o    ../../vibrot.f
gfortran -c -O -o vibs.o      ../../vibs.f
gfortran -c -O -o virial.o    ../../virial.f
gfortran -c -O -o volume.o    ../../volume.f
gfortran -c -O -o warp.o      ../../warp.f
gfortran -c -O -o xtalfit.o   ../../xtalfit.f
gfortran -c -O -o xtalmin.o   ../../xtalmin.f
gfortran -c -O -o xtals.o     ../../xtals.f
gfortran -c -O -o xyzatm.o    ../../xyzatm.f
gfortran -c -O -o xyzedit.o   ../../xyzedit.f
gfortran -c -O -o xyzint.o    ../../xyzint.f
gfortran -c -O -o xyzpdb.o    ../../xyzpdb.f
gfortran -c -O -o xyzsybyl.o  ../../xyzsybyl.f
gfortran -c -O -o zatom.o     ../../zatom.f
gfortran -c -O -o zclose.o    ../../zclose.f
gfortran -c -O -o zcoord.o    ../../zcoord.f
cd ..
