#
#
#  #################################################################
#  ##                                                             ##
#  ##  library.make  --  create object library of TINKER modules  ##
#  ##                   (g95 for Linux Version)                   ##
#  ##                                                             ##
#  #################################################################
#
#
ar -crusv ./a/libtinker.a \
./o/active.o \
./o/analysis.o \
./o/angles.o \
./o/attach.o \
./o/basefile.o \
./o/beeman.o \
./o/bicubic.o \
./o/bitors.o \
./o/bonds.o \
./o/born.o \
./o/bounds.o \
./o/bussi.o \
./o/calendar.o \
./o/center.o \
./o/chkpole.o \
./o/chkring.o \
./o/chkxyz.o \
./o/cholesky.o \
./o/clock.o \
./o/cluster.o \
./o/column.o \
./o/command.o \
./o/connect.o \
./o/connolly.o \
./o/control.o \
./o/cspline.o \
./o/cutoffs.o \
./o/deflate.o \
./o/delete.o \
./o/diagq.o \
./o/diffeq.o \
./o/eangang.o \
./o/eangang1.o \
./o/eangang2.o \
./o/eangang3.o \
./o/eangle.o \
./o/eangle1.o \
./o/eangle2.o \
./o/eangle3.o \
./o/ebond.o \
./o/ebond1.o \
./o/ebond2.o \
./o/ebond3.o \
./o/ebuck.o \
./o/ebuck1.o \
./o/ebuck2.o \
./o/ebuck3.o \
./o/echarge.o \
./o/echarge1.o \
./o/echarge2.o \
./o/echarge3.o \
./o/echgdpl.o \
./o/echgdpl1.o \
./o/echgdpl2.o \
./o/echgdpl3.o \
./o/edipole.o \
./o/edipole1.o \
./o/edipole2.o \
./o/edipole3.o \
./o/egauss.o \
./o/egauss1.o \
./o/egauss2.o \
./o/egauss3.o \
./o/egeom.o \
./o/egeom1.o \
./o/egeom2.o \
./o/egeom3.o \
./o/ehal.o \
./o/ehal1.o \
./o/ehal2.o \
./o/ehal3.o \
./o/eimprop.o \
./o/eimprop1.o \
./o/eimprop2.o \
./o/eimprop3.o \
./o/eimptor.o \
./o/eimptor1.o \
./o/eimptor2.o \
./o/eimptor3.o \
./o/elj.o \
./o/elj1.o \
./o/elj2.o \
./o/elj3.o \
./o/embed.o \
./o/emetal.o \
./o/emetal1.o \
./o/emetal2.o \
./o/emetal3.o \
./o/emm3hb.o \
./o/emm3hb1.o \
./o/emm3hb2.o \
./o/emm3hb3.o \
./o/empole.o \
./o/empole1.o \
./o/empole2.o \
./o/empole3.o \
./o/energy.o \
./o/eopbend.o \
./o/eopbend1.o \
./o/eopbend2.o \
./o/eopbend3.o \
./o/eopdist.o \
./o/eopdist1.o \
./o/eopdist2.o \
./o/eopdist3.o \
./o/epitors.o \
./o/epitors1.o \
./o/epitors2.o \
./o/epitors3.o \
./o/erf.o \
./o/erxnfld.o \
./o/erxnfld1.o \
./o/erxnfld2.o \
./o/erxnfld3.o \
./o/esolv.o \
./o/esolv1.o \
./o/esolv2.o \
./o/esolv3.o \
./o/estrbnd.o \
./o/estrbnd1.o \
./o/estrbnd2.o \
./o/estrbnd3.o \
./o/estrtor.o \
./o/estrtor1.o \
./o/estrtor2.o \
./o/estrtor3.o \
./o/etors.o \
./o/etors1.o \
./o/etors2.o \
./o/etors3.o \
./o/etortor.o \
./o/etortor1.o \
./o/etortor2.o \
./o/etortor3.o \
./o/eurey.o \
./o/eurey1.o \
./o/eurey2.o \
./o/eurey3.o \
./o/evcorr.o \
./o/extra.o \
./o/extra1.o \
./o/extra2.o \
./o/extra3.o \
./o/fatal.o \
./o/fft3d.o \
./o/fftpack.o \
./o/field.o \
./o/final.o \
./o/flatten.o \
./o/freeunit.o \
./o/geometry.o \
./o/getint.o \
./o/getkey.o \
./o/getmol.o \
./o/getmol2.o \
./o/getnumb.o \
./o/getpdb.o \
./o/getprm.o \
./o/getref.o \
./o/getstring.o \
./o/gettext.o \
./o/getword.o \
./o/getxyz.o \
./o/ghmcstep.o \
./o/gradient.o \
./o/gradrgd.o \
./o/gradrot.o \
./o/groups.o \
./o/grpline.o \
./o/gyrate.o \
./o/hessian.o \
./o/hessrgd.o \
./o/hessrot.o \
./o/hybrid.o \
./o/image.o \
./o/impose.o \
./o/induce.o \
./o/inertia.o \
./o/initatom.o \
./o/initial.o \
./o/initprm.o \
./o/initres.o \
./o/initrot.o \
./o/insert.o \
./o/invbeta.o \
./o/invert.o \
./o/jacobi.o \
./o/kangang.o \
./o/kangle.o \
./o/katom.o \
./o/kbond.o \
./o/kcharge.o \
./o/kdipole.o \
./o/kewald.o \
./o/kextra.o \
./o/kgeom.o \
./o/kimprop.o \
./o/kimptor.o \
./o/kinetic.o \
./o/kmetal.o \
./o/kmpole.o \
./o/kopbend.o \
./o/kopdist.o \
./o/korbit.o \
./o/kpitors.o \
./o/kpolar.o \
./o/ksolv.o \
./o/kstrbnd.o \
./o/kstrtor.o \
./o/ktors.o \
./o/ktortor.o \
./o/kurey.o \
./o/kvdw.o \
./o/lattice.o \
./o/lbfgs.o \
./o/lights.o \
./o/makeint.o \
./o/makeref.o \
./o/makexyz.o \
./o/maxwell.o \
./o/mdinit.o \
./o/mdrest.o \
./o/mdsave.o \
./o/mdstat.o \
./o/mechanic.o \
./o/merge.o \
./o/molecule.o \
./o/moments.o \
./o/mutate.o \
./o/nblist.o \
./o/nextarg.o \
./o/nexttext.o \
./o/nose.o \
./o/nspline.o \
./o/number.o \
./o/numeral.o \
./o/numgrad.o \
./o/ocvm.o \
./o/openend.o \
./o/optsave.o \
./o/orbital.o \
./o/orient.o \
./o/orthog.o \
./o/overlap.o \
./o/picalc.o \
./o/pmestuff.o \
./o/pmpb.o \
./o/polymer.o \
./o/precise.o \
./o/pressure.o \
./o/prmkey.o \
./o/promo.o \
./o/prtdyn.o \
./o/prterr.o \
./o/prtint.o \
./o/prtmol2.o \
./o/prtpdb.o \
./o/prtprm.o \
./o/prtseq.o \
./o/prtxyz.o \
./o/quatfit.o \
./o/random.o \
./o/rattle.o \
./o/readdyn.o \
./o/readgau.o \
./o/readint.o \
./o/readmol.o \
./o/readmol2.o \
./o/readpdb.o \
./o/readprm.o \
./o/readseq.o \
./o/readxyz.o \
./o/replica.o \
./o/respa.o \
./o/rgdstep.o \
./o/rings.o \
./o/rmsfit.o \
./o/rotlist.o \
./o/rotpole.o \
./o/sdstep.o \
./o/search.o \
./o/server.o \
./o/shakeup.o \
./o/sigmoid.o \
./o/sktstuff.o \
./o/sort.o \
./o/square.o \
./o/suffix.o \
./o/surface.o \
./o/surfatom.o \
./o/switch.o \
./o/temper.o \
./o/tncg.o \
./o/torphase.o \
./o/torque.o \
./o/torsions.o \
./o/trimtext.o \
./o/unitcell.o \
./o/verlet.o \
./o/version.o \
./o/volume.o \
./o/xyzatm.o \
./o/zatom.o
