mkdir noopenmp-obj
cd noopenmp-obj

@echo off
rem
rem
rem  #############################################################
rem  ##                                                         ##
rem  ##  compile.make  --  compile each of the TINKER routines  ##
rem  ##           (Intel Fortran for Windows Version)           ##
rem  ##                                                         ##
rem  #############################################################
rem
rem
rem  compile all the modules; "sizes" must be first since it is used
rem  to set static array dimensions in many of the other modules
rem
rem
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sizes.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../action.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../align.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../analyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../angang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../angbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../angpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../angtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../argue.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ascii.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../atmlst.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../atomid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../atoms.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bath.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bitor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bndpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bndstr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bound.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../boxes.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../cell.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../charge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../chgpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../chrono.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../chunks.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../couple.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../deriv.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../dipole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../disgeo.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../dma.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../domega.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../energi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ewald.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../faces.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../fft.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../fields.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../files.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../fracs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../freeze.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../gkstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../group.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../hescut.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../hessn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../hpmf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ielscf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../improp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../imptor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../inform.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../inter.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../iounit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kanang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kangs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kantor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../katoms.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kbonds.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kchrge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kdipol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../keys.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../khbond.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kiprop.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kmulti.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kopbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kopdst.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../korbs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kpitor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kpolr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kstbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ksttor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ktorsn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ktrtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kurybr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kvdwpr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kvdws.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../light.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../limits.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../linmin.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../math.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mdstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../merck.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../minima.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../molcul.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../moldyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../moment.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mplpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mrecip.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mutant.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../neigh.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nonpol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nucleo.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../omega.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../opbend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../opdist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../openmp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../orbits.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../output.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../params.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../paths.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pbstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../phipsi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../piorbs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pistuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pme.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../polar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../polgrp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../polpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../potent.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../potfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../precis.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ptable.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../qmstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../refer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../resdue.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../restrn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rgddyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ring.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rotbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rxnfld.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rxnpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../scales.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sequen.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../shunt.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../socket.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../solute.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../stodyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../strbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../strtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../syntrn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../tarray.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../titles.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../torpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../tors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../tortor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../tree.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../units.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../uprior.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../urey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../urypot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../usage.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../usolve.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../valfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../vdw.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../vdwpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../vibs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../virial.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../warp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xtals.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../zclose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../zcoord.f
rem
rem  now compile separately each of the Fortran source files
rem
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../active.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../alchemy.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../analysis.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../analyze.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../angles.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../anneal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../archive.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../attach.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../basefile.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../beeman.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bicubic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bonds.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../born.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bounds.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../bussi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../calendar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../center.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../chkpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../chkring.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../chkxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../cholesky.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../clock.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../cluster.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../column.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../command.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../connect.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../connolly.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../control.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../correlate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../crystal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../cspline.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../cutoffs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../deflate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../delete.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../diagq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../diffeq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../diffuse.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../distgeom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../document.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../dynamic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangang1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangang2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangang3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangle1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangle2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangle3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangtor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangtor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eangtor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebond.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebond1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebond2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebond3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebuck.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebuck1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebuck2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ebuck3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echarge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echarge1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echarge2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echarge3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echgdpl.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echgdpl1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echgdpl2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../echgdpl3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../edipole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../edipole1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../edipole2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../edipole3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egauss.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egauss1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egauss2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egauss3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egeom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egeom1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egeom2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../egeom3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ehal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ehal1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ehal2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ehal3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimprop.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimprop1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimprop2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimprop3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimptor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimptor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimptor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eimptor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../elj.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../elj1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../elj2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../elj3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../embed.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emetal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emetal1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emetal2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emetal3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emm3hb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emm3hb1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emm3hb2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../emm3hb3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../empole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../empole1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../empole2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../empole3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../energy.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopbend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopbend1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopbend2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopbend3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopdist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopdist1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopdist2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eopdist3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epitors1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epitors2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epitors3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epolar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epolar1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epolar2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../epolar3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../erf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../erxnfld.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../erxnfld1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../erxnfld2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../erxnfld3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../esolv.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../esolv1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../esolv2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../esolv3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrbnd1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrbnd2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrbnd3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrtor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrtor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../estrtor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etors1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etors2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etors3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etortor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etortor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etortor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../etortor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eurey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eurey1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eurey2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../eurey3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../evcorr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../extra.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../extra1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../extra2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../extra3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../fatal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../fft3d.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../fftpack.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../field.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../final.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../flatten.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../freeunit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../gda.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../geometry.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getkey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getmol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getmol2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getnumb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getref.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getstring.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../gettext.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getword.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../getxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ghmcstep.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../gradient.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../gradrgd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../gradrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../groups.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../grpline.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../gyrate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../hessian.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../hessrgd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../hessrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../hybrid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../image.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../impose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../induce.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../inertia.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../initatom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../initial.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../initprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../initres.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../initrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../insert.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../intedit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../intxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../invbeta.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../invert.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../jacobi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kangang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kangle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kangtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../katom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kbond.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kcharge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kdipole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kewald.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kextra.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kgeom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kimprop.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kimptor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kinetic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kmetal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kmpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kopbend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kopdist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../korbit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kpitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kpolar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ksolv.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kstrbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kstrtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ktors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ktortor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kurey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../kvdw.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../lattice.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../lbfgs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../lights.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../makeint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../makeref.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../makexyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../maxwell.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mdinit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mdrest.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mdsave.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mdstat.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mechanic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../merge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../minimize.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../minirot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../minrigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../molecule.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../molxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../moments.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../monte.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../mutate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nblist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../newton.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../newtrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nextarg.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nexttext.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nspline.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../nucleic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../number.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../numeral.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../numgrad.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../ocvm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../openend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../optimize.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../optirot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../optrigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../optsave.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../orbital.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../orient.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../orthog.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../overlap.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../path.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pdbxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../picalc.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pmestuff.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pmpb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../polarize.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../poledit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../polymer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../potential.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../precise.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pressure.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prmedit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prmkey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../promo.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../protein.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prtdyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prterr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prtint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prtmol2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prtpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prtprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prtseq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../prtxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pss.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pssrigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../pssrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../qrfact.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../quatfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../radial.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../random.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rattle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readdyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readgau.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readmol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readmol2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readseq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../readxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../replica.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../respa.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rgdstep.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rings.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rmsfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rotlist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../rotpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../saddle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../scan.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sdstep.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../search.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../server.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../shakeup.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sigmoid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../simplex.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sktstuff.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sniffer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sort.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../spacefill.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../spectrum.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../square.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../suffix.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../superpose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../surface.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../surfatom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../switch.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../sybylxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../temper.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../testgrad.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../testhess.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../testpair.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../testpol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../testrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../timer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../timerot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../tncg.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../torphase.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../torque.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../torsfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../torsions.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../trimtext.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../unitcell.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../valence.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../verlet.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../version.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../vibbig.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../vibrate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../vibrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../volume.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xtalfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xtalmin.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xyzatm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xyzedit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xyzint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xyzpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../xyzsybyl.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../zatom.f

ifort /c /O3 /QxHost /Qip- /Qprec-div- /w ../../testhesssparse-htna.f

cd ..
