using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HTLib2.Bioinfo
{
    public partial class HSequence
	{
        /// Selecting lstPdbsSim30 in matlab as following way
        /// 
        /// 1. Q ← sort all 258 proteins whose residue number is >=60 (decreasing order)
        /// 2. S ← {}
        /// 3. while (Q is not empty)
        /// 4.   q ← pop from Q (removing the first(largest) element from Q, and return to q)
        /// 5.   add ← true
        /// 5.   forall (s in S)
        /// 6.     if (nwalign(s,q) > size(q)* 30%), then (add ← false)
        /// 6.   if (add == true), then (S ← S ∪ q)
        /// 7. return S
        /// 

        public static IList<Tuple<string, T>> GetListDissim<T>(IList<Tuple<string, T>> sequences, double similarity=0.3)
        {
            Tuple<string, object>[] seq1 = new Tuple<string, object>[sequences.Count];
            for(int i=0; i<sequences.Count; i++) seq1[i] = new Tuple<string, object>(sequences[i].Item1, sequences[i].Item2);

            Tuple<string, object>[] seq2 = GetListDissim(seq1, similarity).ToArray();

            Tuple<string,T>[] seq3 = new Tuple<string, T>[seq2.Length];
            for(int i=0; i<seq2.Length; i++) seq3[i] = new Tuple<string, T>(seq2[i].Item1, (T)(seq2[i].Item2));

            return seq3;
        }
        public static IList<Tuple<string, object>> GetListDissim(IList<Tuple<string, object>> sequences, double similarity=0.3)
        {
            int[] lstSeqLeng = new int[sequences.Count];
            for(int i=0; i<sequences.Count; i++) lstSeqLeng[i] = sequences[i].Item1.Length;

            Tuple<string, object>[] Q = sequences.HSelectByIndex(lstSeqLeng.HIdxSorted().HReverse());
            List<Tuple<string, object>> S = new List<Tuple<string, object>>();
            foreach(var q in Q)
            {
                bool add = true;
                foreach(var s in S)
                {
                    double score = Nwalign(s.Item1, q.Item1).Score;
                    if(score > q.Item1.Length * similarity)
                    {
                        add = false;
                        break;
                    }
                }
                if(add)
                    S.Add(q);
            }

            return S;
        }
    }
}

/**
function testsim()
    IdAllCaSeq = GetIdAllCaSeq();
    
    % select whose res size > 60
    IdAllCaSeq = IdAllCaSeq(([IdAllCaSeq{:,3}]') >= 60,:);
    
    res30 = GetDissim(IdAllCaSeq, 0.30);
    fprintf('number proteins remained with 30 percent : %d\n',length(res30));
    res50 = GetDissim(IdAllCaSeq, 0.50);
    fprintf('number proteins remained with 50 percent : %d\n',length(res50));
end

function result = GetDissim(IdAllCaSeq, x)
    % sort Q by nres
    [~,Qi] = sort([IdAllCaSeq{:,3}]','descend'); Qi = Qi';
    % S = {}
    S = [];
    % iterate
    for qi = Qi
        if(length(S) == 0)
            S = [qi];
        else
            qseq = IdAllCaSeq{qi,4};
            bAddToS = true;
            for si = S
                sseq = IdAllCaSeq{si,4};
                sim = nwalign(sseq, qseq);
                if(sim > length(qseq)*x)
                    bAddToS = false;
                    break;
                end
            end
            if(bAddToS)
                S = [S, qi];
            end
        end
    end
    result = IdAllCaSeq(S,:);
end

function IdAllCaSeq = GetIdAllCaSeq()
    IdAllCaSeq=[%{pdbid, num atom, num residue, sequence}
                {'3SGP', 0186,011, 'KLKVLGDVIEV'}
                {'3SGR', 0390,025, 'GKLKVLGDVIEVGGKLKVLGDVIEV'}
                {'3TWE', 0465,026, 'GNADELYKELEDLQERLRKLRKKLRS'}
                {'2WQ0', 0512,031, 'MKQLEDKIEENTSKIYHNTNEIARNTKLVGE'}
                {'2JKU', 0497,035, 'TSSVLRSPMPGVVVAVSVKPGDAVAEGQEICVIEA'}
                {'1T6F', 0629,037, 'TLYEALKENEKLHKEIEQKDNEIARLKKENKELAEVA'}
                {'1Z96', 0539,038, 'GLNSKIAQLVSMGFDPLEAAQALDAANGDLDVAASFLL'}
                {'1GK7', 0657,039, 'GSNEKVELQELNDRFANYIDKVRFLEQQNKILLAELEQL'}
                {'3H00', 0652,039, 'NNYTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWFN'}
                {'2IZX', 0648,039, 'IPPGLTELLQGYTVEVLRQQPPDLVEFAVEYFTRLREAR'}
                {'3VEJ', 0652,040, 'VDLTVPWDDIEALLKNNFENDQAAVRQVMERLQKGWSLAK'}
                {'3G9R', 0786,042, 'ELDKWASLWNWFNITNWLWYIKIEELKSKIKRIENEIKRIKK'}
                {'2HO2', 0513,033, 'SDLPAGWMRVQDTSGTYYWHIPTGTTQWEPPGR'}
                {'3M9H', 0715,043, 'SARDIHQLEARIDSLAARNSKLMETLKEARQQLLALREEVDRL'}
                {'3B0F', 0674,043, 'DPRLIESLSQMLSMGFSDEGGWLTRLLQTKNYDIGAALDTIQY'}
                {'2XUS', 0721,041, 'ERRRSECVSEMLDLEKQFSELKEKLFRERLSQLRLRLEEVG'}
                {'3SSU', 0788,046, 'SRLGDLYEEEMRELRRQVDQLTNDKARVEVERDNLAEDIMRLREKL'}
                {'3SWY', 0743,046, 'GALEEKVEQLGSSLDTLQTRFARLLAEYNATQMKMKQRLSQLESQV'}
                {'2OEI', 0555,037, 'GSDLPAGWMRVQDTSGTYYWHIPTGTTQWEPPGRASP'}
                {'3VMY', 0812,048, 'GSERQILRLKQINIQLATKIQHLEFSCSEKEQEIERLNKLLKQNGLLG'}
                {'3VMX', 0812,048, 'GSERQILRLKQINIQLATKIQHLEFSCSEKEQEIERLNKLLKQNGLLG'}
                {'2XF7', 0737,048, 'ESLLYGYFLDSWLDGTASEELLRVAVNAGDLTQEEADKIMSYPWGAWN'}
                {'2A26', 0819,048, 'HMASEELQKDLEEVKVLLEKATRKRVRDALTAEKSKIETEIKNKMQQK'}
                {'2XF6', 0760,050, 'SESLLYGYFLDSWLDGTASEELLRVAVNAGDLTQEEADKIMSYPWGAWND'}
                {'1JCD', 0664,050, 'NAKADQASSDAQTANAKADQASNDANAARSDAQAAKDDAARANQRADNAA'}
                {'2RKL', 0850,053, 'GSTKDELTKIMDRASKIEQIQKLAKYAISALNYEDLPTAKDELTKALDLLNSI'}
                {'2X48', 0880,054, 'MKKEIQVQGVRYYVESEDDLVSVAHELAKMGYTVQQIANALGVSERKVRRYLES'}
                {'3KBL', 0901,054, 'SHEATVEYLADLVKEKKHLTLFPHMFSAVERLLDDEIGRVRVALFQTEFPRVEL'}
                {'2A28', 0773,054, 'GAMEAIYAYEAQGDDEISIDPGDIITVIRGDDGSGWTYGECDGLKGLFPTSYCK'}
                {'3K6T', 0905,054, 'SHEATVEYLADLVKEKKHLTLFPHMFSNVERLLDDEIGRVRVALFQTEFPRVEL'}
                {'4DCZ', 0865,055, 'QNKDPDELRSKVPGEVTASDWEALVGDTRYGYFDETGDWSWKGYFDEQGKWVWNE'}
                {'2ON8', 0877,056, 'MQFKLIINGKTLKGEITLEAVDAAEAEKKFKQYANDNGIDGEWTYDDATKTFTVTE'}
                {'2ONQ', 0875,056, 'MQFKLIINGKTLKGEITIEAVDAAEAEKFFKQYANDNGIDGEWTYDDATKTFTVTE'}
                {'3HSH', 0914,056, 'GSSGVRLWATRQAMLGQVHEVPEGWLIFVAEQEELYVRVQNGFRKVQLEARTPLPR'}
                {'3TSI', 0754,050, 'SPSSGLGSITDLLNNILSVANQIIYNSAVALPLQLDTLESTLLTAIKSLQ'}
                {'3NGP', 0964,057, 'KELVLVLYDYQEKSPRELTVKKGDILTLLNSTNKDWWKIEVNGRQGFVPAAYLKKLD'}
                {'3SFM', 0870,058, 'DATFGMGDRVRKKSGAAWQGQIVGWYCTNLTPEGYAVESEAHPGSVQIYPVAALERIN'}
                {'3M0U', 0950,058, 'GKELVLALYDYQEKSPDEVTMKKGDILTLLNSTNKDWWKVEVNDRQGFVPAAYVKKLD'}
                {'3M0R', 0950,058, 'GKELVLALYDYQEKSPDEVTMKKGDILTLLNSTNKDWWKVEVNDRQGFVPAAYVKKLD'}
                {'2OVG', 0918,058, 'QRITLKDYAMRFGQTKTAKDLGVYPSSINQAIHAGRKIFLTINADGSVYAEEVKPFPS'}
                {'1OOT', 0900,058, 'SPKAVALYSFAGEESGDLPFRKGDVITILKKSDSQNDWWTGRVNGREGIFPANYVELV'}
                {'1I2T', 0968,061, 'HRQALGERLYPRVQAMQPAFASKITGMLLELSPAQLLLLLASEDSLRARVDEAMELIIAHG'}
                {'3MCE', 0919,057, 'GPLGSPEFSKLGLRQVTGVTRVTIRKSKNILFVITKPDVYKSDTYIVFGEAKIEDLS'}
                {'3P7J', 0930,059, 'TGFDRGLEAEKILGASDNNGRLTFLIQFKGVDQAEMVPSSVANEKIPRMVIHFYEERLS'}
                {'2J5Y', 0978,061, 'LVPRGSHMTIDQWLLKNAKEDAIAELKKAGITSDFYFNAINKAKTVEEVNALKNEILKAHA'}
                {'1Y0M', 0996,061, 'TFKSAVKALFDYKAQREDELTFTKSAIIQNVEKQDGGWWRGDYGGKKQLWFPSNYVEEMIN'}
                {'3MP9', 0931,061, 'HHHAMDTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDDATKTFTVTE'}
                {'2IGD', 0927,061, 'MTPAVTTYKLVINGKTLKGETTTKAVDAETAEKAFKQYANDNGVDGVWTYDDATKTFTVTE'}
                {'1G2B', 1011,062, 'MSGTGKELVLALYDYQEKSPREVTMKKGDILTLLNSTNKDWWKVEVNDRQGFVPAAYVKKLD'}
                {'3QWS', 0973,062, 'MKPEELVRHFGDVEKAAVGVGVTPGAVYQWLQAGEIPPLRQSDIEVRTAYKLKSDFTSQRMG'}
                {'4B27', 0991,064, 'SDFVVIKAVEDGVNVIGLTRGTDTKFHHSEKLDKGEVIIAQFTEHTSAIKVRGEALIQTAYGEM'}
                {'3ZR8', 1053,065, 'GPTEKAAVKKMAKAIMADPSKADDVYQKWADKGYTLTQLSDFLKSKTRGKYDRVYNGYMTYRDYV'}
                {'3ZZQ', 1013,065, 'SDFVVIKAVEDGVNVIGLTRGTDTKFHHSEKLDKGEVIIAQFTEHTSAIKVRGEALIQTAYGEMK'}
                {'3BD1', 0991,065, 'MNAIDIAINKLGSVSALAASLGVRQSAISNWRARGRVPAERCIDIERVTNGAVICRELRPDVFGA'}
                {'2HIN', 1035,066, 'MKPEELVRHFGDVEKAAVGVGVTPGAVYQWLQAGEIPPLRQSDIEVRTAYKLKSDFTSQRMGKEGH'}
                {'3HFO', 1025,065, 'DSGLPSVRQVQLLIKDQTPVEIKLLTGDSLFGTIRWQDTDGLGLVDDSERSTIVRLAAIAYITPR'}
                {'1TG0', 1029,066, 'EPEVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEWYFGEYQDSNGDVIEGIFPKSFVAVQG'}
                {'1HG7', 1009,066, 'MNQASVVANQLIPINTALTLVMMRSEVVTPVGIPAEDIPRLVSMQVNRAVPLGTTLMPDMVKGYAA'}
                {'3RNJ', 1052,067, 'GPLGSGRMRVKAIFSHAAGDNSTLLSFKEGDLITLLVPEARDGWHYGESEKTKMRGWFPFSYTRVLD'}
                {'2O31', 1083,067, 'GIDPFTGEAIAKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRIPGTSRQGIFPITYVDVIKRPL'}
                {'2VE8', 1045,067, 'EDDPLYDEAVRFVTESRRASISAVQRKLKIGYNRAARMIEAMEMAGVVTPMNTNGSREVIAPAPVRD'}
                {'3I4O', 1137,068, 'GAIEVEGRVVEPLPNAMFRIELENGHKVLAHISGKMRQHYIRILPEDRVVVELSPYDLSRGRIVYRYK'}
                {'3OMT', 1120,068, 'TERKIFNRLKSVLAEKGKTNLWLTETLDKNKTTVSKWCTNDVQPSLETLFDIAEALNVDVRELIVSTK'}
                {'2YIZ', 1037,068, 'SNHTYRVIEIVGTSPDGVDAAIQGGLARAAQTMRALDWFEVQSIRGHLVDGAVAHFQVTMKVGFRLED'}
                {'1WYX', 1077,068, 'LNVLAKALYDNVAESPDELSFRKGDIMTVLEQDTQGLDGWWLCSLHGRQGIVPGNRLKILVGMYDKKP'}
                {'4B6X', 1086,069, 'GAGAALRQEIEDKQLMVNNLTDELQDAIDEANPAEIANTSQQLRHARADLADLQRRFAVLRNEDRRINQ'}
                {'3ZZL', 1103,070, 'SNFFVIKAKENGVNVFGMTRGTDTRFHHSEKLDKGEVMIAQFTEHTSAVKIRGKAIIQTSYGTLDTEKDE'}
                {'3NAR', 1155,070, 'GKICKKTPEQLHMLKSAFVRTQWPSPEEYDKLAKESGLARTDIVSWFGDTRYAWKNGNLKWYYYYQSANS'}
                {'1WM3', 1169,072, 'HINLKVAGQDGSVVQFKIKRHTPLSKLMKAYCERQGLSMRQIRFRFDGQPINETDTPAQLEMEDEDTIDVFQ'}
                {'3LNQ', 1020,058, 'RYRTTFTSFQLEELEKAFSRTHYPDVFTREELAMKIGLTEARIQVWFQNRRAKWRKQE'}
                {'1IHR', 1176,073, 'ARAQALRIEGQVKVKFDVTPDGRVDNVQILSAKPANMFEREVKNAMRRWRYEPGKPGSGIVVNILFKINGTTE'}
                {'3E56', 1239,075, 'LEVGVYECEIHLKFRLIEEKSLLSDREQLLQVLLDALTEGSDDFLETLQASVKAQEVSEFKASPQMRRQLMRLRN'}
                {'3NTW', 0961,061, 'GSHRQALGERLYPRVQAMQPAFASKITGMLLELSPAQLLLLLASEDSLRARVEEAMELIVA'}
                {'3L1X', 1210,075, 'SDAPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNRQTLTESMLEPVPELKEQIQAWMREKQNS'}
                {'4GSW', 1199,074, 'NAMQIFVKTLTGKTITLEVEPNDSIDAIKAKIQEKEGIPPDQQRLIFAGKQLEEGKTLSDYNIQKESTLHLVLR'}
                {'3IGE', 1145,075, 'GGYVNIKTFTHPAGEGKEVKGMEVSVPFEIYSNEHRIADAHYQTFPSEKAAYTTVVTDAADWRTKNAAMFTPTPV'}
                {'3B7H', 1198,076, 'MKTDGEFVSEHLMELITQQNLTINRVATLAGLNQSTVNAMFEGRSKRPTITTIRKVCGTLGISVHDFFDFPPYNEV'}
                {'2IC6', 1143,071, 'STLKEVQDNITLHEQRLVTTRQKLKDAERAVELDPDDVNKSTLQSRRAAVSALETKLGELKRELADLIAAQ'}
                {'4HK2', 1216,074, 'GSMQIFVKFRTGKTYTLEVEPSDTIENVKAKIQDKLGIPPDQQWLIFAGKRLEDGRTLSDYNIQKESTLRGVRR'}
                {'2PMR', 1255,076, 'CRERIEKDLELLEKNLMEMKSIKLSDDEEAVVERALNYRDDSVYYLEKGDHITSFGCITYAHGLLDSLRMLHRIIE'}
                {'3Q9Q', 1190,077, 'SHTADRWRVSLDVNHFAPDELTVKTKDGVVEITGKHAARYISRCFTRKYTLPPGVDPTQVSSSLSPEGTLTVEAPMP'}
                {'2VKL', 1248,077, 'EIDTLREEIDRLDAEILALVKRRAEVSKAIGKARMASGGTRLVHSREMKVIERYSELGPDGKDLAILLLRLGRGRLG'}
                {'3G21', 1198,077, 'AGPWADIMQGPSESFVDFANRLIKAVEGSDLPPSARAPVIIDCFRQKSQPDIQQLIRTAPSTLTTPGEIIKYVLDRQ'}
                {'3IG9', 1145,075, 'GGYVNIKTFTHPAGEGKEVKGMEVSVPFEIYSNEHRIADAHYQTFPSEKAAYTTVVTDAADWRTKNAAMFTPTPV'}
                {'4F26', 1209,077, 'GNIFIKNLDKSIDNKALYDTFSAFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKS'}
                {'2O9V', 1083,067, 'GIDPFTGEAIAKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRIPGTSRQGIFPITYVDVIKRPL'}
                {'4ABM', 1328,079, 'GAMEQEAIQRLRDTEEMLSKKQEFLEKKIEQELTAAKKHGTKNKRAALQALKRKKRYEKQLAQIDGTLSTIEFQREALE'}
                {'2QCP', 1265,080, 'MEAQPQVISATGVVKGIDLESKKITIHHDPIAAVNWPEMTMRFTITPQTKMSEIKTGDKVAFNFVQQGNLSLLQDIKVSQ'}
                {'3MCB', 0874,054, 'AMSKLGLRQVTGVTRVTIRKSKNILFVITKPDVYKSPASDTYIVFGEAKIEDLS'}
                {'4AGH', 1259,080, 'GSQVDAEGNPFWEISDKRRVGISQFKKMDFINIREYYEAGGEMKPGKKGIGLTVDQYTAFLKAIPAINAELRSRGHDITD'}
                {'3N27', 1168,073, 'KNADNINKLKSSIESTNEAVVKLQETAEKTVYVLTALQDYGIDISIELNKAKSDLEESKEWIRRSNQKLDSIG'}
                {'2GBN', 1250,081, 'MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGGGGGGGGGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRL'}
                {'2O37', 1281,081, 'MVKETKLYDLLGVSPSANEQELKKGYRKAALKYHPDKPTGDTEKFKEISEAFEILNDPQKREIYDQYGLEAARSGGPSFGP'}
                {'3LLB', 1284,081, 'SYIKPLPSGDFIVKALTPVDAFNDFFGSEFSDEEFDTVGGLVMSAFGHLPKRNEVVELGEFRFRVLNADSRRVHLLRLSPL'}
                {'3O5Z', 1263,082, 'GPEGFQYRALYPFRRERPEDLELLPGDVLVVSRAALQALGVAEGGERCPQSVGWMPGLNERTRQRGDFPGTYVEFLGPVALA'}
                {'1R6J', 1233,082, 'GAMDPRTITMHKDSTGHVGFIFKNGKITSIVKDSSAARNGLLTEHNICEINGQNVIGLKDSQIADILSTSGTVVTITIMPAF'}
                {'4ERR', 1294,082, 'GQIFTVQELKERAKVFAKPIGASYQGILDQLDLVHQAKGRDQIAASFELNKKINDYIAEHPTSGRNQALTQLKEQVTSALGL'}
                {'3R3M', 1373,082, 'ENAEPVSKLRIRTPSGEFLERRFLASNKLQIVFDFVASKGFPWDEYKLLSTFPRRDVTQLDPNKSLLEVKLFPQETLFLEAK'}
                {'3RQ9', 1196,078, 'NLKPQTLMVAIQCVAARTRELDAQLQNDDPQNAAELEQLLVGYDLAADDLKNAYEQALGQYSGLPPYDRLIEEPASLE'}
                {'2GBJ', 1250,081, 'MQIFVKTLTGGGGGGGGGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRL'}
                {'4ES3', 1370,084, 'HMMLVLITYDVQTSSMGGTKRLRKVAKACQNYGQRVQNSVFECIVDSTQLTSLKLELTSLIDEEKDSLRIYRLNYKVEHIGAKP'}
                {'1W53', 1425,084, 'MDFREVIEQRYHQLLSRYIAELTETSLYQAQKFSRKTIEHQIPPEEIISIHRKVLKELYPSLPEDVFHSLDFLIEVMIGYGMAY'}
                {'3R27', 1283,084, 'KTPASPVVHIRGLIDGVVEADLVEALQEFGPISYVVVMPKKRQALVEFEDVLGACNAVNYAADNQIYIAGHPAFVNYSTSQKIS'}
                {'4E6S', 1397,085, 'GRPRPEVAHQLFRCFQYQEDMGPRASLGRLRELCNHWLRPALHTKKQILELLVLEQFLSVLPPHVLSRLHGAPLRDGEEVAQLEG'}
                {'3CCD', 1287,085, 'MFEQEVTITAPNGLDTRPAAQFVKEAKGFTSEITVTSNGKSASAKSLFKLQTLGLTQGTVVTISAEGEDEQKAVEHLVKLMAELE'}
                {'2F5K', 1401,083, 'DPKPKFQEGERVLCFHGPLLYEAKCVKVAIKDKQVKYFIHYSGWNKNWDEWVPESRVLKYVDTNLQKQRELQKANQEQYAEGK'}
                {'3VBG', 1432,084, 'TLVRPKPELLKLLKSVGAQKDTYTMKEVLFYLGQYIMTKRLYDEKQQHIVYCSNDLLGDLFGVPSFSVKEHRKIYTMIYRNLVV'}
                {'3TPX', 1436,084, 'TLVRPKPLLLKLLKSVGAQKDTYTMKEVLFYLGQYIMTKRLYDEKQQHIVYCSNDLLGDLFGVPSFSVKEHRKIYTMIYRNLVV'}
                {'1YO3', 1367,085, 'GSVVKNVDMTEEMQIDAIDCANQALQKYNVEKDIAAHIKKEFDRKYDPTWHCVVGRNFGSYVTHETKNFIYFYIGQVAILLFKSG'}
                {'2RK5', 1352,086, 'QSREIADNTYIVLGTMTLNDFNEYFETDLESDNVDTIAGFYLTGVGTIPSQEEKEHFEVESNGKHLELINDKVKDGRVTKLKILVS'}
                {'3TOE', 1342,086, 'NVVYIGNKPVMNYVLAVVTQMNGGTSEVILKARGIAISRAVDVAEIVRNRFIPDIQIENIDICTEEIIGNEGTATNVSAIEIQLRK'}
                {'3LNW', 1338,086, 'MKEVTIEIKNKTGLHARPAALFVQTASKFSSQIWVEKDNKKVNAKSIMGIMSLGVSQGNVVKLSAEGDDEEEAIKALVDLIESKFG'}
                {'3N4W', 1332,087, 'EYGYIVTDQKPLSLAAGVKLLEILAEHVHMSSGSFINIAVVGPALTFRIRHNEQNLSLADVTQQAGLVKSELEAQTGLQILQTGVGQ'}
                {'3FX7', 1414,084, 'QMDTEEVREFVGHLERFKELLREEVNSLSNHFHNLESWRDARRDKFSEVLDNLKSTFNEFDEAAQEQIAWLKERIRVLEEDYLE'}
                {'3ZW2', 1262,087, 'MQTAAISWGTTPSIRVYTANGNKITERCYDGSNWYTGAFNQAGDNVSATCWLSGSAVHIRVYATSGGSTTEWCWDGDGWTRGAYTGL'}
                {'3JQU', 1257,086, 'GSAPIAKVTGPSTGAVGRNIEFSGKDSKDEDGKIVSYDWDFGDGATSRGKNSVHAYKKAGTYNVTLKVTDDKGATATESFTIEIKN'}
                {'3R69', 1284,085, 'SPRVVVIKKGSNGYGFYLRAGPGQIIKDIEPGSPAEAAGLKNNDLVVAVNGKSVEALDHDGVVEMIRKGGDQTTLLVLDKQEAKL'}
                {'3RJS', 1410,087, 'DRKAVIKNADMPEDLQQDAIDCANQALEKYNIEKDIAAFIKKEFDRKHNPTWHCVVGRNFGSYVTHETHHFIYFYIGQVAVLLFKSG'}
                {'3TXQ', 1417,087, 'VYAPLVLRDPVSNPNNRKIDQDDDYELVRRNMHYQSQMLLDMAKIALENAKNADSPRHVEVFAQLMGQMTTTNKEMLKMHKEMKDLA'}
                {'3BRI', 1419,087, 'DRKAVIKNADMSEEMQQDAVDCATQALEKYNIEKDIAAYIKKEFDKKYNPTWHCIVGRNFGSYVTHETRHFIYFYLGQVAILLFKSG'}
                {'2Y4X', 1341,087, 'KPDETRVKQFLEGFNIETFEMVGTLSNAQGTFALVKGAGGVHRVRVGDYLGRNDGKVVGISEGKIDVIEIVPDGEGNWLERPRSLTL'}
                {'4HTI', 1356,088, 'ARGYIVTDRDPLRPEEGRRLVEDVARLLQVPSSAFADVEVLGPAVTFKVSANVQNVTTEDVEKATVDNKDKLEETSGLKILQTGVGSK'}
                {'4HTJ', 1367,089, 'ARGYIVTDRDPLRPEEGRRLVEDVARLLQVPSSAFADVEVLGPAVTFKVSANVQNVTTEDVEKATVDNKDKLEETSGLKILQTGVGSKS'}
                {'3DS4', 1174,076, 'TSILDIRQGPKEPFRDYVDRFYKTLRAEASQEVKNWMTETLLVQNANPDCKTILKALGPGATSEEMMTACQGVGGP'}
                {'3ID3', 1354,089, 'MIEPVLENVQPNSAASKAGLQAGDRIVKVDGQPLTQWVTFVMLVRDNPGKSLALEIERQGSPLSLTLIPESKPGNGKAIGFVGAEPKVI'}
                {'4HE6', 1455,089, 'SLKTTREFAGLVLGYDPETGIATVQQRNHFRPGDEVEFFGPEIENFTQVIEKIWDEDGNELDAARHPLQIVKFKVKRPLFPYNMMRKEN'}
                {'3CNK', 1395,089, 'KVVAKGLGLSKAYVGQKSSFTVDCSKAGNNMLLVGVHGPRTPCEEILVKHVGSRLYSVSYLLKDKGEYTLVVKWGHEHIPGSPYRVVVP'}
                {'3MAB', 1352,085, 'LANLSELPNIGKVLEQDLIKAGIKTPVELKDVGSKEAFLRIWENDSSVCMSELYALEGAVQGIRWHGLDEAKKIELKKFHQSLEG'}
                {'1U07', 1439,090, 'ASGPRALSRNQPQYPARAQALRIEGQVKVKFDVTPDGRVDNVQILSAKPANMFEREVKNAMRRWRYEPGKPGSGIVVNILFKINGTTEIQ'}
                {'3PE9', 1368,090, 'MVKLTAPKSNVVAYGNEFLKITATASDSDGKISRVDFLVDGEVIGSDREAPYEYEWKAVEGNHEISVIAYDDDDAASTPDSVKIFVKQAR'}
                {'3ID2', 1381,090, 'HMIEPVLENVQPNSAASKAGLQAGDRIVKVDGQPLTQWVTFVMLVRDNPGKSLALEIERQGSPLSLTLIPESKPGNGKAIGFVGIEPKVI'}
                {'2BT9', 1326,090, 'SSVQTAATSWGTVPSIRVYTANNGKITERCWDGKGWYTGAFNEPGDNVSVTSWLVGSAIHIRVYASTGTTTTEWCWDGNGWTKGAYTSTN'}
                {'4GS3', 1491,090, 'ENNTVTLVGKVFTPLEFSHELYGEKFFNFILEVPRLSETKDYLPITISNRLFEGMNLEVGTRVKIEGQLRSYNRKLILTVFARDISVVPE'}
                {'4AEQ', 1466,090, 'KGPACYQVSDEQARTFVKNDYLQRMKRWDNDVQLLGTEIPKITWEKIERSLTDVEDEKTLLVPFKAEGPDGKRMYYGMYHCEEGYVEYAN'}
                {'3JTN', 1390,089, 'DIIYQFHSFEDIIQLSESLQRIGITGGTVYHYDGQYFLSLEDLGSHTAEGVVAVLAEYGNPTTLTIYRLQEYGKLIMDGNAVETIQTHF'}
                {'3MSH', 1326,090, 'MEATLEQHLEDTMKNPSIVGVLCTDSQGLNLGCRGTLSDEHAGVISVLAQQAAKLTSDPTDIPVVCLESDNGNIMIQKHDGITVAVHKMA'}
                {'3KOV', 1511,090, 'GRKKIQITRIMDERNRQVTFTKRKFGLMKKAYELSVLCDCEIALIIFNSSNKLFQYASTDMDKVLLKYTEYNEPHESRTNSDIVEALNKK'}
                {'3M8J', 1418,090, 'GGDAFLLKLRESALSSGSMSEEQFFLLIGISSIHSDRVILAMKDYLVSGHSRKDVCEKYQMNNGYFSTTLGRLTRLNVLVARLAPYYTDS'}
                {'3TXS', 1441,089, 'QVYAPLVLRDPVSNPNNRKIDQDDDYELVRRNMHYQSQMLLDMAKIALENAKNADSPRHVEVFAQLMGQMTTTNKEMLKMHKEMKDLAG'}
                {'4EWI', 1616,091, 'FFSDFGLMWYLEELKKEEFRKFKEHLKQMTLQLELKQIPWTEVKKASREELANLLIKHYEEQQAWNITLRIFQKMDRKDLCMKVMRERTGY'}
                {'2X3D', 1392,090, 'GMAIRRLVLDVLKPIRGTSIVDLAERISKLDGVEGVNISVTDMDVETMGLMIIIEGTSLNFDDIRKMLEEEGCAIHSIDEVVSGNRIIEG'}
                {'4GMQ', 1411,092, 'NAVKKNKRVLRGSVKEANYFVEGEASAATIDAVLNDVDLVITKIDADEIAALAGKLNGLTVADEIKNVWKEEVSRLVGAGKLKEGDIKALVA'}
                {'3QWG', 1457,093, 'TTFAARLNRLFDTVYPPGRGPHTSAEVIAALKAEGITMSAPYLSQLRSGNRTNPSGATMAALANFFRIKAAYFTDDEYYEKLDKELQWLCTMR'}
                {'3ID4', 1408,093, 'MIEPVLENVQPNSAASKAGLQAGDRIVKVDGQPLTQWVTFVMLVRDNPGKSLALEIERQGSPLSLTLIPESKPGNGKAIGFVGIEPKGKASPV'}
                {'4IOG', 1363,087, 'NAMAEIKITPEELERIAGNFKNAAGEAQSQINRLEGDINSLEGQWAGATQAKFRGEFIQSKQAMQQYIPILEGISTDLKRIADKFRN'}
                {'2X5T', 1561,093, 'ASLKEIIDELGKQAKEQNKIASRILKIKGIKRIVVQLNAVPQDKIRYSLTIHSQNNFRKQIGITPQDAEDLKLIAEFLEKYSDFLNEYVKFTP'}
                {'2I5C', 1551,094, 'VIIKQGCLLKQGHRRKNWKVRKFILREDPAYLHYYDPAGAEDPLGAIHLRGCVVTSVEENLFEIITADEVHYFLQAATPKERTEWIKAIQMASR'}
                {'3KJL', 1413,086, 'QLKSQIQQYLVESGNYELISNELKARLLQEGWVDKVKDLTKSEMNINESTNFTQILSTVEPKALEMVSDSTRETVLKQIREFLEEI'}
                {'3ID1', 1435,094, 'MVRPVVGEIAANSIAAEAQIAPGTELKAVDGIETPDWDAVRLQLVDKIGDESTTITVAPFGSDQRRDVKLDLRHWAFEPDKEDPVSSLGIRPRG'}
                {'3L7H', 1379,086, 'LKRIQSHKGVVGTIVVNNEGIPVKSTLDNTTTVQYAGLMSQLADKARSVVRDLDPSNDMTFLRVRSKKHEIMVAPDKDFILIVIQN'}
                {'3KIK', 1525,094, 'MDTAQLKSQIQQYLVESGNYELISNELKARLLQEGWVDKVKDLTKSEMNINESTNFTQILSTVEPKALEMVSDSTRETVLKQIREFLEEIVDTQ'}
                {'4EZA', 1558,094, 'KPVKYTAAKLHEKGVLLDIDDLQTNQFKNVTFDIIATEDVGIFDVRSKFLGVEMEKVQLNIQDLLQMQYEGVAVMKMFDKVKVNVNLLIYLLNK'}
                {'1G2R', 1570,094, 'RKIPLRKSVVSNEVIDKRDLLRIVKNKEGQVFIDPTGKANGRGAYIKLDNAEALEAKKKKVFNRSFSMEVEESFYDELIAYVDHKVKRRELGLE'}
                {'2FE5', 1420,094, 'SMTIMEVNLLKGPKGLGFSIAGGIGNQHIPGDNSIYITKIIEGGAAQKDGRLQIGDRLLAVNNTNLQDVRHEEAVASLKNTSDMVYLKVAKPGS'}
                {'1C5E', 1376,095, 'SDPAHTATAPGGLSAKAPAMTPLMLDTSSRKLVAWDGTTDGAAVGILAVAADQTSTTLTFYKSGTFRYEDVLWPEAASDETKKRTAFAGTAISIV'}
                {'3SQF', 1546,095, 'KPSLTLWLDDKMFTGLINTGADVTIIKLEDWPPNWPITDTLTNLRGIGQSNNPKQSSKYLTWRDKENNSGLIKPFVIPNLPVNLWGRDLLSQMKI'}
                {'4FQN', 1533,095, 'GSKTISESELSASATELLQDYMLTLRTKLSSQEIQQFAALLHEYRNGASIHEFCINLRQLYGDSRKFLLLGLRPFIPEKDSQHFENFLETIGVKD'}
                {'2Y2T', 1477,095, 'SSQITFNTTQQGDMYTIIPEVTLTQSCLCRVQILSLREGSSGQSQTKQEKTLSLPANQPIALTKLSLNISPDDRVKIVVTVSDGQSLHLSQQWPP'}
                {'3SHU', 1474,094, 'GPGSMKLVKFRKGDSVGLRLAGGNDVGIFVAGVLEDSPAAKEGLEEGDQILRVNNVDFTNIIREEAVLFLLDLPKGEEVTILAQKKKDVYRRIV'}
                {'2X5H', 1518,092, 'GMASLKEIIDELGKQAKEQNKIASRIMKIKGIKRIVVQLNAVPQDGKIRYSMTIHSQNNFRKQIGITPQDAEDLKLIAEFLEKYSDFLNEYV'}
                {'4A75', 1360,089, 'GSDPQVLRGSGHCKWFNVRMGFGFISMTSREGSPLENPVDVFVHQSKLYMEGFRSLKEGEPVEFTFKKSSKGFESLRVTGPGGNPCLGN'}
                {'3PYJ', 1592,096, 'GEWEIIDIGPFTQNLAKFAVDEENKIGQYGRLTFNKVIRPCMKKTIYENEGFREIKGYEYQLYVYASDKLFRADISEDYKTRGRKLLRFNGPVPPP'}
                {'2WJ5', 1449,096, 'GAMAQVPTDPGYFSVLLDVKHFSPEEISVKVVGDHVEVHARHEERPDEHGFIAREFHRRYRLPPGVDPAAVTSALSPEGVLSIQATPASAQASLPS'}
                {'3RZW', 1354,089, 'SSVPTKLEVVAATPTSLLISWDAGYWFIDYYRITYGETGGNSPVQEFTVPGYSSTATISGLSPGVDYTITVYAYYDNYGWSPISINYRT'}
                {'1URR', 1592,097, 'VAKQIFALDFEIFGRVQGVFFRKHTSHEAKRLGVRGWCMNTRDGTVKGQLEAPMMNLMEMKHWLENNRIPNAKVSKAEFSQIQEIEDYTFTSFDIKH'}
                {'4E35', 1339,087, 'GPIRKVLLLKEDHEGLGISITGGKEHGVPILISEIHPGQPADRCGGLHVGDAILAVNGVNLRDTKHKEAVTILSQQRGEIEFEVVYV'}
                {'3L1F', 1549,097, 'SEVRSDRDKFVIFLDVKHFSPEDLTVKVQEDFVEIHGKHNERQDDHGYISREFHRRYRLPSNVDQSALSCSLSADGMLTFSGPKIPSGVERAIPVSR'}
                {'3E2B', 1419,087, 'DRKAVIKNADMSEEMQQDAVDCATQALEKYNIEKDIAAYIKKEFDKKYNPTWHCIVGRNFGSYVTHETRHFIYFYLGQVAILLFKSG'}
                {'1JO0', 1555,097, 'TTLSTKQKQFLKGLAHHLNPVVMLGGNGLTEGVLAEIENALNHHELIKVKVAGADRETKQLIINAIVRETKAAQVQTIGHILVLYRPSEEAKIQLPR'}
                {'3VI6', 1550,097, 'KSLESINSRLQLVMKSGKYVLGYKQTLKMIRQGKAKLVILANNCPALRKSEIEYYAMLAKTGVHHYSGNNIELGTACGKYYRVCTLAIIDPGDSDII'}
                {'4E34', 1339,087, 'GPIRKVLLLKEDHEGLGISITGGKEHGVPILISEIHPGQPADRCGGLHVGDAILAVNGVNLRDTKHKEAVTILSQQRGEIEFEVVYV'}
                {'2Y9R', 1481,098, 'RGIPPKIEALPSDISIDEGKVLTVACAFTGEPTPEVTWSCGGRKIHSQEQGRFHIENTDDLTTLIIMDVQKQDGGLYTLSLGNEFGSDSATVNIHIRS'}
                {'3PO8', 1506,098, 'GTSVTLQLDDGSGRTYQLREGSNIIGRGQDAQFRLPDTGVSRRHLEIRWDGQVALLADLNSTNGTTVNNAPVQEWQLADGDVIRLGHSEIIVRMHPLT'}
                {'3KNG', 1544,098, 'ADEVTFVNRFTVHGAPAEFESVFARTAAFFARQPGFVRHTLLRERDKDNSYVNIAVWTDHDAFRRALAQPGFLPHATALRALSTSEHGLFTARQTLPE'}
                {'3BRL', 1434,088, 'SDRKAVIKNADMSEEMQQDAVDCATQALEKYNIEKDIAAYIKKEFDKKYNPTWHCIVGRNFGSYVTHETRHFIYFYLGQVAILLFKEG'}
                {'3QMX', 1519,099, 'MRGSHHHHHHGSAVSAKIEIYTWSTCPFCMRALALLKRKGVEFQEYCIDGDNEAREAMAARANGKRSLPQIFIDDQHIGGCDDIYALDGAGKLDPLLHS'}
                {'2QJL', 1542,099, 'MVNVKVEFLGGLDAIFGKQRVHKIKMDKEDPVTVGDLIDHIVSTMINNPNDVSIFIEDDSIRPGIITLINDTDWELEGEKDYILEDGDIISFTSTLHGG'}
                {'3QMQ', 1583,097, 'SMHVTLVEINVHEDKVDEFIEVFRQNHLGSVQEEGNLRFDVLQDPEVNSRFYIYEAYKDEDAVAFHKTTPHYKTCVAKLESLMTGPRKKRLFNGLMP'}
                {'3NS6', 1576,099, 'GPLGSDQYIVVNGAPVIPSAKVPVLKKALTSLFSKAGKVVNMEFPIDEATGKTKGFLFVECGSMNDAKKIIKSFHGKRLDLKHRLFLYTMKDVERYNSD'}
                {'3BZY', 0264,017, 'SGSLANNIKKSTVIVKN'}
                {'3K6F', 1545,100, 'SGIVVSPILIPENQRQPFPRDVGKVVDSDRPEGSKFRLTGKGVDQDPKGTFRINENTGSVSVTRTLDRETIATYQLYVETTDASGKTLEGPVPLEVIVID'}
                {'2XRH', 1606,100, 'AIDPFTMAKDFSKTSDEDLAKMAGVVAPQDIVDYTKELKKRMEKMPEDKRKAFHKQLHEYATKNTDKMTVADFEARQKAVKEALKKGNMEDMDDDFGLRS'}
                {'3NXA', 1620,100, 'DCYTELEKAVIVLVENFYKYVSKYSLVKNKISKSSFREMLQKELNHMLSDTGNRKAADKLIQNLDANHDGRISFDEYWTLIGGITGPIAKLIHEQEQQSS'}
                {'3RHB', 1602,100, 'SRMEESIRKTVTENTVVIYSKTWCSYCTEVKTLFKRLGVQPLVVELDQLGPQGPQLQKVLERLTGQHTVPNVFVCGKHIGGCTDTVKLNRKGDLELMLAE'}
                {'3RL8', 1443,094, 'KIMEIKLIKGPKGLGFSIAGGVGNQHIPGDNSIYVTKIIEGGAAHKDGKLQIGDKLLAVNNVCLEEVTHEEAVTALKNTSDFVYLKVAKPTSMY'}
                {'3SSQ', 1539,101, 'MPIAVGMIETRGFPAVVEAADAMVKAARVTLVGYEKIGSGRVTVIVRGDVSEVQASVAAGVDSAKRVNGGEVLSTHIIARPHENLEYVLPIRYTEAVEQFR'}
                {'3U1C', 1617,101, 'AGHMDAIKKKMQMLKLDKENALDRAEQAEADKKAAEERSKQLEDDIVQLEKQLRVTEDSRDQVLEELHKSEDSLLFAEENAAKAESEVASLNRRIQLVEEE'}
                {'1MG4', 1656,101, 'KKAKKVRFYRNGDRYFKGIVYAISPDRFRSFEALLADLTRTLSDNVNLPQGVRTIYTIDGLKKISSLDQLVEGESYVCGSIEPFKKLEYTKNVNPNWSVNV'}
                {'3QGL', 1460,096, 'SPRVVRIVKSESGYGFNVRGQVSEGGQLRSINGELYAPLQHVSAVLPGGAADRAGVRKGDRILEVNGVNVEGATHKQVVDLIRAGEKELILTVLSV'}
                {'1MFG', 1454,095, 'GSMEIRVRVEKDPELGFSISGGVGGRGNPFRPDDDGIFVTRVQPEGPASKLLQPGDKIIQANGYSFINIEHGQAVSLLKTFQNTVELIIVREVSS'}
                {'3M9J', 1633,105, 'MVKQIESKTAFQEALDAAGDKLVVVDFSATWCGPCKMIKPFFHSLSEKYSNVIFLEVDVDDCQDVASESEVKSMPTFQFFKKGQKVGEFSGANKEKLEATINELV'}
                {'3FG7', 1705,106, 'NLVITPRLFECSNKTGRFLATEIPDFNQDDLEEDDVFLLDVWDQVFFWIGKHANEEEKKAAATTAQEYLKTHPSGRDPETPIIVVKQGHEPPTFTGWFLAWDPFKW'}
                {'4D8D', 0890,057, 'TLFVALYDYEAWTEDDLSFHKGEKFQILNSSEGDWWEARSLTTGETGYIPSNYVAPV'}
                {'3CX2', 1674,107, 'DDPIGLFVMRPQDGEVTVGGSITFSARVAGALLKPPVVKWFKGKWVDLSSKVGQHLQLHDSYDRASKVYLFELHITDAQPAFTGSYRCEVSTKDKFDCSNFNLTVHE'}
                {'1BKR', 1762,108, 'KSAKDALLLWCQMKTAGYPNVNIHNFTTSWRDGMAFNALIHKHRPDLIDFDKLKKSNAHYNLQNAFNLAEQHLGLTKLLDPEDISVDHPDEKSIITYVVTYYHYFSKM'}
                {'4A9F', 1813,108, 'VTNQLQYLHKVVMKALWKHQFAWPFRQPVDAVKLGLPDYHKIIKQPMDMGTIKRRLENNYYWAASECMQDFNTMFTNCYIYNKPTDDIVLMAQTLEKIFLQKVASMPQ'}
                {'3HTU', 1203,075, 'RRPEEWGKLIYQWVSRSGQNNSVFTLYELTNGEDTEDEEFHGLDEATLLRALQALQQEHKAEIITVSDGRGVKFF'}
                {'4BBD', 1905,114, 'MRTLLIRYILWRNDNDQTYYNDDFKKLMLLDELVDDGDVSTLIKNMRMTLSDGPLLDYLNQPVNNIEDAKRMIAISAKVARDIGERSEIRWEESFTILFRMIETYFDDLMIDLY'}
                {'3LRG', 1650,114, 'SQPVLTQSPSVSAAPRQRVTISVSGSNSNIGSNTVNWIQQLPGRAPELLMYDDDLLAPGVSDRFSGSRSGTSASLTISGLQSEDEADYYAATWDDSLNGWVFGGGTKVTVLSAH'}
                {'2Y3E', 1731,120, 'GITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAEGDYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVKP'}
                {'2ZWM', 1954,120, 'DKKILVVDDEKPIADILEFNLRKEGYEVHCAHDGNEAVEMVEELQPDLILLDIMLPNKDGVEVCREVRKKYDMPIIMLTAKDSEIDKVIGLEIGADDYVTKPFSTRELLARVKANLRRQL'}
                {'4GCO', 1938,120, 'YINPELAQEEKNKGNEYFKKGDYPTAMRHYNEAVKRDPENAILYSNRAACLTKLMEFQRALDDCDTCIRLDSKFIKGYIRKAACLVAMREWSKAQRAYEDALQVDPSNEEAREGVRNCLR'}
                {'3T6L', 1746,120, 'GITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAESRFVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVKP'}
                {'2CKK', 1962,120, 'TARTDYWLQPEIIVKIITKKLGEKYHKKKAIVKEVIDKYTAVVKMIDSGDKLKLDQTHLETVIPAPGKRILVLNGGYRGNEGTLESINEKTFSATIVIETGPLKGRRVEGIQYEDISKLA'}
                {'4A6S', 1764,121, 'AWKGEVLANNEAGQVTSIIYNPGDVITIVAAGWASYGPTQKWGPQGDREHPDQGLICHDAFCGALVMKIGNSGTIPVNTGLFRWVAPNNVQGAITLIYNDVPGTYGNNSGSFSVNIGKDQS'}
                {'2YH5', 1817,121, 'TTMDVQSAADDTGLPMLVVRGPFNVVWQRLPAALEKVGMKVTDSTRSQGNMAVTYKPLSDSDWQELGASDPGLASGDYKLQVGDLDNRSSLQFIDPKGHTLTQSQNDALVAVFQAAFSKLE'}
                {'3TDM', 1856,120, 'QAVVVAIDAKRVDGEFMVFTYSGKKNTGILLRDWVVEVEKRGAGEILLTSIDRDGTKSGYDTEMIRFVRPLTTLPIIASGGAGKMEHFLEAFLRGADKVSINTAAVENPSLITQIAQTFG'}
                {'2Y3F', 1741,121, 'AGITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAEGDYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVKP'}
                {'3LKY', 1739,121, 'SLTHRKFGGSGGSPFSGLSSIAVRSGSYLDAIIIDGVHHGGSGGNLSPTFTFGSGEYISNMTIRSGDYIDNISFETNMGRRFGPYGGSGGSANTLSNVKVIQINGSAGDYLDSLDIYYEQY'}
                {'3RE6', 1733,121, 'TAEAGITGTWYNQLGSTLIVTAGADGALTGTYESNAESSYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSASTWSGQYVGGAEARINTQVLTTSGTTEANAWKSTLVGHDTFTKVKP'}
                {'2QCB', 1781,122, 'DEAGITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAESRYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTKGTTEANAWKSTLVGHDTFTKVK'}
                {'2WPU', 1770,122, 'DEAGITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAESRYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVK'}
                {'3CPO', 1882,122, 'LPTAQEVQGLMARYIELVDVGDIEAIVQMYADDATVENPFGQPPIHGREQIAAFYRQGLKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVIDVMRFDEHGRIQTMQAYWSEVNLSV'}
                {'3NJM', 1850,122, 'APQGLAQFIKVNVTLENGEPVFIYTDANGQVCQGDITVTQAGTITYLLNDQTLKGLKFVGVGFVTPFDGIIDAVTISSDGMLVQLVDLDKTPGTTKFQFVLSNTANTLLVLSPDAQIINRPQ'}
                {'3NJK', 1852,122, 'APQGLAQFIKVNVTLENGEPVFIYTDANGQVCQGDITVTQAGTITYLLNDQTLKGLKFVGVGFVTPFDGIIDAVTISSDGMLVQLVDLDKTPGTTKFQFVLSNTANTLLVLSPAPQIINRPQ'}
                {'1R29', 2000,122, 'SQIQFTRHASDVLLNLNRLRSRDILTDVVIVVSREQFRAHKTVLMACSGLFYSIFTDQLKRNLSVINLDPEINPEGFNILLDFMYTSRLNLREGNIMAVMATAMYLQMEHVVDTCRKFIKAS'}
                {'1MK5', 1758,121, 'EAGITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAESRYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVK'}
                {'3T6F', 1757,121, 'EAGITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAESRFVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVK'}
                {'3OV4', 1819,120, 'MNTPEHMTAVVQRYVAALNAGDLDGIVALFADDATVEDEPRSGTAAIREFYANSLKLPLAVELTQEVRAVANEAAFAFTVSFEYQGRKTVVAPIDHFRFNGAGKVVSMRALFGEKNIHAG'}
                {'3RNV', 2016,123, 'MYIAKEGYCYINIFLAMLVNVKESQAKEFTKVVRDKLVGELGKWPTLLDVATACYFLKVFYPDVANAELPRMLVDHKTKIIHVVDSYGSLSTGYHVLKTNTVEQLIKFTRCNLESSLKHYRVG'}
                {'3RDM', 1748,123, 'TAEAGITGTWYNQLGSTLIVTAGADGALTGTYESAVGNAEGSYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSASTWSGQYVGGAEARINTQVLTTSGTTEANAWKSTLVGHDTFTKVK'}
                {'3RY2', 1758,121, 'EAGITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAESRYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVK'}
                {'2PZV', 1896,123, 'NLPTAQEVQGLMARYIELVDVGDIEAIVQMYADDATVENPFGQPPIHGREQIAAFYRQGLKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVIDVMRFDEHGRIQTMQAYWSEVNLSV'}
                {'3P38', 1958,123, 'KMPASRYLTDMTLEEMSRDWFMLMPKQKVAGSLCIKMDQAIMDKTIILKANFSVIFDRLETLILLRAFTEEGAIVGEISPLPSLPGHTGEDVKNAIGVLIGGLEANDNTVRVTETIQRFAWRN'}
                {'3P6J', 1848,123, 'KGDTHIQFQISPEGNGEVLLKSTETGQYLRINPDGTVDGTDRSDTHIQFQISPEGNGEVLLKSTETGQYLRINPDGTVDGTDRSDTHIQFQISPEGNGEVLLKSTETGQYLRINPDGTVDGTR'}
                {'3RDS', 1748,123, 'TAEAGITGTWYNQLGSTLIVTAGADGALTGTYESAVGNAEGSYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSASTWSGQYVGGAEARINTQVLTTSGTTEANAWKSTLVGHDTFTKVK'}
                {'3UJ3', 2004,124, 'LIGYVRVATNDQNTDLQRNALVCAGCEQIFEDKLSGTRTDRPGLKRALKRLQKGDTLVVWKLDRLGRSMKHLISLVGELRERGINFRSLTDSIDTSSPMGRFFFHVMGALAEVERELIIERTMA'}
                {'3T8U', 1846,123, 'MNTPEHMTAVVQRAVAALNAGDLDGIVALFADDATVEDPVGSEPRSGTAAIREFFANSLKLPLAVELTQEVRAVANEAAFAFTVSFEYQGRKTVVAPIAHFRFNGAGKVVSMRALFGEKNIHA'}
                {'1MM9', 1796,124, 'GITGTWYNQLGSTFIVTAGADGALTGTYESAVGNAESRYVLTGRYDSAPRGDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVKPSAAS'}
                {'4E6I', 1998,123, 'LHKEPATLIKAIDGNTVKLMYKGQPMVFRLLLVDIYGPEAAAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKMGNEALVRQGLAKVAYVYKGNNTHEQHLRKAEAQAKKEKLNIWS'}
                {'3IPT', 1910,124, 'NLPTAQEVQGLMARSIELVDVGDIEAIVQMYADDATVENPFGQPPIHGREQIAAFYRQGLKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVIDVMRFDEHGRIQTMQAYWSEVNLSVR'}
                {'3MHE', 1819,120, 'MNTPEHMTAVVQRYVAALNAGDLDGIVALFADDATVEDEPRSGTAAIREFYANSLKLPLAVELTQEVRAVANEAAFAFTVSFEYQGRKTVVAPIDHFRFNGAGKVVSMRALFGEKNIHAG'}
                {'3PA7', 1911,124, 'QETLEQVHLTEDGGVVKTILRKGEGGEENAPKKGNEVTVHYVGKLESSGKVFDSSRERNVPFKFHLGQGEVIKGWDICVASMTKNEKCSVRLDSKYGYGEEGCGESIPGNSVLIFEIELISFRE'}
                {'4HBX', 2122,127, 'SMNPPPPETSNPNKPKRQTNQLQYLLRVVLKTLWKHQFAWPFQQPVDAVKLNLPDYYKIIKTPMDMGTIKKRLENNYYWNAQECIQDFNTMFTNCYIYNKPGDDIVLMAEALEKLFLQKINELPTEE'}
                {'1DBF', 2062,127, 'MMIRGIRGATTVERDTEEEILQKTKQLLEKIIEENHTKPEDVVQMLLSATPDLHAVFPAKAVRELSGWQYVPVTCMQEMDVTGGLKKCIRVMMTVQTDVPQDQIRHVYLEKAVVLRPDLSLTKNTEL'}
                {'2VZC', 2087,127, 'ERDAFDTLFDHAPDKLNVVKKTLITFVNKHLNKLNLEVTELETQFADGVYLVLLMGLLEGYFVPLHSFFLTPDSFEQKVLNVSFAFELMQDGGLEKPKPRPEDIVNCDLKSTLRVLYNLFTKYRNVE'}
                {'1N9M', 1757,121, 'EAGITGTWYNQLGATFIVTAGADGALTGTYESAVGNAESRYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQYVGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVK'}
                {'2YEL', 2122,127, 'SMNPPPPETSNPNKPKRQTNQLQYLLRVVLKTLWKHQFAWPFQQPVDAVKLNLPDYYKIIKTPMDMGTIKKRLENNYYWNAQECIQDFNTMFTNCYIYNKPGDDIVLMAEALEKLFLQKINELPTEE'}
                {'4GCN', 2041,127, 'SNAMTDAAIAEKDLGNAAYKQKDFEKAHVHYDKAIELDPSNITFYNNKAAVYFEEKKFAECVQFCEKAVEVGRETRADYKLIAKAMSRAGNAFQKQNDLSLAVQWFHRSLSEFRDPELVKKVKELEK'}
                {'3VA9', 2044,127, 'TNKALLAISAIQQAVLEAETSERGFLLTGIETYRDSYIRARDALAARLDGLRAVLADNPEQIAHIDELRLLTDMRMAQLGRVVELGPERMREALDILEQARVDRLTERIETSLSVLTRAEQALLIQR'}
                {'3VGN', 1934,127, 'MNLPTAQEVQGLMARYIELVDVGDIEAIVQMYADDATVENPFGQPPIHGREQIAAFYRQGLGGGKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVIDVMRFDEHGRIQTMQAYWSEVNLSV'}
                {'3R45', 1356,082, 'HLLIRKLPFSRLAREICVKFTRGVDFNWQAQALLALQEAAEAFLVHLFEDAYLLTLHAGRVTLFPKDVQLARRIRGLEEGLG'}
                {'2XX6', 2099,128, 'MQIKIKYLDETQTRINKMEQGDWIDLRAAEDVAIKKDEFKLVPLGVAMELPEGYEAHVVPRSSTYKNFGVIQTNSMGVIDESYKGDNDFWFFPAYALRDTKIKKGDRICQFRIMKKMPAVDLIEVDRL'}
                {'4F55', 1953,128, 'GGGRTNVPNGYSQNDIQLMANAVYGESRGEPYLGQVAVAAVILNRVTSASFPNTVSGVIFEPRAFTAVADGQIYLTPNETAKKAVLDAINGWDPTGNALYYFNPDTATSKWIWTRPQIKKIGKHIFCK'}
                {'4DRO', 1987,128, 'GAPATVTEQGEDITSKKDRGVLKIVKRVGNGEETPMIGDKVYVHYKGKLSNGKKFDSSHDRNEPFVFSLGKGQVIKAWDIGVATMKKGEICHLLCKPEYAYGSAGSLPKIPSNATLFFEIELLDFKGE'}
                {'3RGR', 1949,128, 'MNLPTAQEVQGLMARYIELVDVGDIEAIVQMYADDATVEDPFGQPPIHGREQIAAFYRQGLGGGKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVIDVMRFDEHGRIQTAQAYWSEVNLSVR'}
                {'4DRP', 1987,128, 'GAPATVTEQGEDITSKKDRGVLKIVKRVGNGEETPMIGDKVYVHYKGKLSNGKKFDSSHDRNEPFVFSLGKGQVIKAWDIGVATMKKGEICHLLCKPEYAYGSAGSLPKIPSNATLFFEIELLDFKGE'}
                {'4HTH', 2106,129, 'LHKEPATLIKAIDGDTVKLMYKGQPMVFRLLLVDIPEFNEKYGPEAAAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKMVNEALVRQGLAKVAYVYKGNNTHEQLLRKAEAQAKKEKLNIWS'}
                {'2AAJ', 1964,129, 'ALLKFDLFYGRTDAQIKSLLDAAHGAMVDAFGVPANDRYQTVSQHRPGEMVLEDTGLGYGRSSAVVLLTVISRPRSESQKVCFYKLLTGALERDCGISPDDVIVALVENSDADWSFGRGRAEFLTGDLV'}
                {'3SK4', 2101,129, 'LHKEPATLIKAIDGNTEKLMYKGQPMTFRLLLVDTPEFNEKYGPEASAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKMVNEALVRQGLAKVAYVYKGNNTHEQLLRKAEAQAKKEKLNIWS'}
                {'3SK8', 2090,129, 'LHKEPATLIKAIDGDTVKLMYKGQPMTFRLLLVDTPEFNEKYGPEASAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKGVNEALVRQGLAKVAYVYKGNNTHEQLLRKAEAQAKKEKLNIWS'}
                {'3LRD', 1856,129, 'HTTPWTNPGLAENFMNSFMQGLSSMPGFTASQLDNMSTIAQSMVQSIQSLAAQGRTSPNKLQALNMAFASSMAEIAASQEGGGSLSTKTSSIASAMSNAFLQTTGVVNQPFINEITQLVSMFAQAGMND'}
                {'3SK6', 2110,129, 'LHKEPATLIKAIDGNTKKLMYKGQPMVFRELLVDIPEFNEKYGPEAAAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKMVNEALVRQGLAKVAYVYKGNNTHEQLLRKAEAQAKKEKLNIWS'}
                {'3TP5', 2103,129, 'LHKEPATLIKAIDGNTEKLMYKGQPMVFRELLVDIPEFNEKYGPEAAAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKMVNEALVRQGLAKVAYVYKGNNTHEQLLRKAEAQAKKEKLNIWS'}
                {'3TME', 2107,129, 'LHKEPATLIKAIDGNTEKLMYKGQPMVFRLLLVDIPEFNEKYGPEAAAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKMVNEALVRQGLAKVAYVYKGNNTHEQLLRKAEAQAKKEKLNIWS'}
                {'3O48', 2133,129, 'DFWPTLKDAYEPLYPQQLEILRQQVVSEGGPTATIQSRFNYAWGLIKSTDVNDERLGVKILTDIYKEAESRRRECLYYLTIGCYKLGEYSMAKRYVDTLFEHERNNKQVGALKSMVEDKIQKEENLYFQ'}
                {'4EDL', 2145,129, 'RFERDAFDTLFDHAPDKLSVVKKSLITFVNKHLNKLNLEVTELETQFADGVYLVLLMGLLEDYFVPLHHFYLTPESFDQKVHNVSFAFELMLDGGLKKPKARPEDVVNLDLKSTLRVLYNLFTKYKNVE'}
                {'2XW6', 2014,130, 'SHMRALALIAHDAKKEEMVAFCQRHREVLARFPLVATGTTGRRIEEATGLTVEKLLSGPLGGDQQMGARVAEGRILAVIFFRDPLTAQPHEPDVQALLRVCDVHGVPLATNPMAAEALIPWLQSLVGYQT'}
                {'4EDM', 2101,127, 'ERDAFDTLFDHAPDKLSVVKKSLITFVNKHLNKLNLEVTELETQFADGVYLVLLMGLLEDYFVPLHHFYLTPESFDQKVHNVSFAFELMLDGGLKKPKARPEDVVNLDLKSTLRVLYNLFTKYKNVE'}
                {'3U80', 1955,127, 'MTKVIVVNGPNLRQDLDTLRKLCAEWGKDLGLEVEVRQTDDEAEMVRWMHQAADEKTPVVMNPAAFTHYSYALADAAHMVIDENLPLMEVHISNPSVISPVATGTITGMGFYGYKLALDAVAHLLSE'}
                {'3UD8', 2060,129, 'KKPKLLYCSNGGHFLRILPDGTVDGTRDRSDQHIQLQLSAESVGEVYIKSTETGQYLAMDTDGLLYGSQTPNEECLFLERLEENHYNTYISKKHAEKNWFVGLKKNGSCKRGPRTHYGQKAILFLPLPV'}
                {'3HA4', 2081,127, 'EELEAQRQRHNDPRRPPWPLLHQRVVLLREGKGAPEDIALMWEQTKHYYPADWLIPLELTQVLKYSSGKYLQTYVADPDEMRKEVLMQLLNVKYGRVSDPNGGRVNKDVEEIISMAVDDLENMDLNP'}
                {'3FZW', 1936,127, 'MNLPTAQEVQGLMARYIELVDVGDIEAIVQMYADDATVENPFGQPPIHGREQIAAFYRQGLGGGKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVINVMRFDEHGRIQTMQAYWSEVNLSV'}
                {'3T8N', 1955,129, 'NLPTAQEVQGLMARAIELVDVGDIEAIVQMYADDATVEDPFGQPPIHGREQIAAFYRQGLGGGKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVIAVMRFDEHGRIQTMQAYWSEVNLSVREP'}
                {'3QF3', 2045,131, 'STTFAARLNRLFDTVYPPGRGPHTSAEVIAALKAEGITMSAPYLSQLRSGNRTNPSGATMAALANFFRIKAAYFTDDEYYEKLDKELQWLCTMRDDGVRRIAQRAHGLPSAAQQKVLDRIDELRRAEGIDA'}
                {'3OJB', 2102,131, 'MPFAARLNTPMGPGRTVVVKGEVNANAKSFNVDLLAGKSKDIALHLNPRLNIKAFVRNSFLQESWGEEERNITSFPFSPGMYFEMIIYCDVREFKVAVNGVHSLEYKHRFKELSSIDTLEINGDIHLLEVR'}
                {'2LIS', 2241,131, 'HYVEPKFLNKAFEVALKVQIIAGFDRGLVKWLRVHGRTLSTVQKKALYFVNRRYMQTHWANYMLWINKKIDALGRTPVVGDYTRLGAEIGRRIDMAYFYDFLKDKNMIPKYLPYMEEINRMRPADVPVKYM'}
                {'3OBL', 1869,132, 'ALYNVENQWGGSSAPWNEGGQWEIGSRSDQNVVAINVESGDDGQTLNGTMTYAGEGPIGFRATLLGNNSYEVENQWGGDSAPWHSGGNWILGSRENQNVVAINVESGDDGQTLNGTMTYAGEGPIGFKGTLT'}
                {'3R87', 2130,132, 'MSKIYHHPVQIYYEDTDHSGVVYHPNFLKYFERAREHVIDSDKLATLWNDHGLGFAVYKANMIFQDGVEFAEICDIRTSFTLDGKYKTLWRQEVWRPGASRAAVIGDIEMVCLDKEKRLQPVPADILASMMA'}
                {'4FYH', 2007,127, 'RRSVYFCGSIRGGREDQALYARIVSRLRRYGKVLTEGGDQFIHEQNLNWLQQADVVVAEVTQPSLGVGYELGRAVALGKPILCLFRPQSGRVLSAMIRGAADGSRFQVWDYAEGEVETMLDRYFEAY'}
                {'3LLO', 2041,132, 'SPSYTVLGQLPDTDVYIDIDAYEEVKEIPGIKIFQINAPIYYANSDLYSSANIHTVILDFTQVNFMDSVGVKTLAGIVKEYGDVGIYVYLAGCSAQVVNDLTSNRFFENPALKELLFHSIHDAVLGSQVREA'}
                {'3D4W', 2163,132, 'KLHKEPATLIKAIDGDTVKLMYKGQPMTFRLLLVDTPEFNEKYGPEASAFTKKMVENAKKIEVEFDKGQRTDKYGRGLAYIYADGKMVNEALVRQGLRKVAYVYKGNNTHEQLLRKAEAQAKKEKLNIWSED'}
                {'3RSW', 2113,133, 'MVDAFLGTWKLVDSKNFDDYMKSLGVGFATRQVASMTKPTTIIEKNGDILTLKTHSTFKNTEISFKLGVEFDETTADDRKVKSIVTLDGGKLVHLQKWDGQETTLVRELIDGKLILTLTHGTAVCTRTYEKEA'}
                {'4A1H', 2143,133, 'GMSNKFLGTWKLVSSENFDDYMKALGVGLATRKLGNLAKPTVIISKSGDIITIRTESTFKNTEISFKLGQEFEETTADNRKTKSIVTLQRGSLNQVQRWDGKETTIKRKLVNGKMVAECKMKGVVCTRIYEKV'}
                {'3KXY', 2113,133, 'MDLTSKVNRLLAEFAGRIGLPSLSLDEEGMASLLFDEQVGVTLLLLAERERLLLEADVVGIDVLGEGIFRQLASFNRHWHRFDLHFGFDELTGKVQLYAQILAAQLTLECFEATLANLLDHAEFWQRLLPCAS'}
                {'4HX8', 2221,132, 'SMEDYIKQIYMLIEEKGYARVSDIAEALAVHPSSVTKMVQKLDKDEYLIYEKYRGLVLTSKGKKIGKRLVYRHELLEQFLRIIGVDEEKIYNDVEGIEHHLSWNSIDRIGDLVQYFEEDDARKKDLKSIQKK'}
                {'2R8U', 2134,131, 'MAVNVYSTSVTSDNLSRHDMLAWINESLQLNLTKIEQLCSGAAYCQFMDMLFPGSIALKKVKFQAKLEHEYIQNFKILQAGFKRMGVDKIIPVDKLVKGKFQDNFEFVQWFKKFFDANYDGKDYDPVAARQ'}
                {'2R6Q', 1963,138, 'GPSGLGLPAGLYAFNSGGISLDLGINDPVPFNTVGSQFGTAISQLDADTFVISETGFYKITVIANTATASVLGGLTIQVNGVPVPGTGSSLISLGAPIVIQAITQITTTPSLVEVIVTGLGLSLALGTSASIIIEKVA'}
                {'2XG3', 2230,138, 'ALIVPYNLPLPGGVVPRMLITILGTVKPNANRIALDFQRGNDVAFHFNPRFNENNRRVIVCNTKLDNNWGREERQSVFPFESGKPFKIQVLVEPDHFKVAVNDAHLLQYNHRVKKLNEISKLGISGDIDLTSASYTMI'}
                {'2XDH', 2099,138, 'AKTTIIAGSAEAPQGSDIQVPVKIENADKVGSINLILSYPNVLEVEDVLQGSLTQNSLFDYQVEGNQIKVGIADSNGISGDGSLFYVKFRVTTLRNSHALTLQGIEIYDIDGNSVKVATINGTFRIVSQEEAHHHHHH'}
                {'3ZSL', 2237,138, 'MLIVPYNLPLPGGVVPRMLITILGTVKPNANRIALDFQRGNDVAFHFNPRFNENNRRVIVCNTKLDNNWGREERQSVFPFESGKPFKIQVLVEPDHFKVAVNDAHLLQYNHRVKKLNEISKLGISGDIDLTSASYTMI'}
                {'3ZSK', 2237,138, 'MLIVPYNLPLPGGVVPRMLITILGTVKPNANRIALDFQRGNDVAFHFNPRFNENNRRVIVCNTKLDNNWGREERQSVFPFESGKPFKIQVLVEPDHFKVAVNDAHLLQYNHRVKKLNEISKLGISGDIDLTSASYTMI'}
                {'3R85', 2190,138, 'SNRELVVDFLSYKLSQKGYSWSQMAAVKQALREAGDEFELRYRRAFSDLTSQLHITPGTAYQSFEQVVNELFRDGVNWGRIVAFFSFGGALCVESVDKEMQVLVSRIAAWMATYLNDHLEPWIQENGGWDTFVELYGN'}
                {'3Q47', 2129,132, 'SPSAQELKEQGNRLFVGRKYPEAAACYGRAITRNPLVAVYYTNRALCYLKMQQPEQALADCRRALELDGQSVKAHFFLGQCQLEMESYDEAIANLQRAYSLAKEQRLNFGDDIPSALRIAKKKRWNSIEERR'}
                {'3GZ2', 2293,144, 'NESISTAVIDAINSGATLKDINAIPDDMMDDIYSYAYDFYNKGRIEEAEVFFRFLCIYDFYNVDYIMGLAAIYQIKEQFQQAADLYAVAFALGKNDYTPVFHTGQCQLRLKAPLKAKECFELVIQHSNDEKLKIKAQSYLDAIQ'}
                {'2PWO', 2256,144, 'IVQNLQGQMVHQAISPRTLNAWVKVVEEKAFSPEVIPMFSALSEGATPQDLNTMLNTVGGHQAAMQMLKETINEEAAEWDRLHPVHAGPIEPGQMREPRGSDIAGTTSTLQEQIGWMTHNPPIPVGEIYKRWIILGLNKIVRMY'}
                {'2JDC', 2319,145, 'IEVKPINAEDTYELRHRILRPNQPIEACMFESDLLRGAFHLGGYYGGKLISIASFHQAEHSELQGQKQYQLRGMATLEGYREQKAGSSLIKHAEEILRKRGADLLWCNARTSASGYYKKLGFSEQGEVFDTPPVGPHILMYKRIT'}
                {'2JDD', 2319,145, 'IEVKPINAEDTYELRHRILRPNQPIEACMFESDLLRGAFHLGGYYGGKLISIASFHQAEHSELQGQKQYQLRGMATLEGYREQKAGSSLIKHAEEILRKRGADLLWCNARTSASGYYKKLGFSEQGEVFDTPPVGPHILMYKRIT'}
                {'3SEI', 2360,146, 'TREGKSSEAVSQWLTAFQLQLYAPNFISAGYDLPTISRMTPEDLTAIGVTKPGHRKKIAAEISGLSIPDWLPEHKPANLAVWLSMIGLAQYYKVLVDNGYENIDFITDITWEDLQEIGITKLGHQKKLMLAVRKLAELRRHHHHHH'}
                {'1NWW', 2236,145, 'IEQPRWASKDSAAGAASTPDEKIVLEFMDALTSNDAAKLIEYFAEDTMYQNMPLPPAYGRDAVEQTLAGLFTVMSIDAVETFHIGSSNGLVYTERVDVLRALPTGKSYNLSILGVFQLTEGKITGWRDYFDLREFEEAVDLPLRG'}
                {'4F8A', 2313,146, 'DMRADICVHLNRKVFKEHPAFRLASDGCLRALAMEFQTVHCAPGDLIYHAGESVDSLCFVVSGSLEVIQDDEVVAILGKGDVFGDVFWKEATLAQSCANVRALTYCDLHVIKRDALQKVLEFYTAFSHSFSRNLILTYNLRKRIVF'}
                {'2XEM', 2249,145, 'HHHMPDSYVHRHVVTFDETNLVGNVYFAHYLHWQGHCREHFLADHAPGVMAALADGLALVTVDCHADFYAEGSAFDEVEVRMMLDRLDGHRIAMSFDYVRVAPGPPTLLAQGRQTVACMRRAGHGLEPVEVPAELRRALSRYAVV'}
                {'3RKV', 2420,147, 'LKSVEALRQKGNELFVQKDYKEAIDAYRDALTRLDTLILREKPGEPEWVELDRKNIPLYANMSQCYLNIGDLHEAEETSSEVLKREETNEKALFRRAKARIAAWKLDEAEEDLKLLLRNHPAAASVVAREMKIVTERRAEKKADSRV'}
                {'1J8Q', 2135,147, 'AKALIVYGSTTGNTEYTAETIARELADAGYEVDSRDAASVEAGGLFEGFDLVLLGCSTWGDDSIELQDDFIPLFDSLEETGAQGRKVACFGCGDSSYEYFCGAVDAIEEKLKNLGAEIVQDGLRIDGDPRAARDDIVGWAHDVRGAI'}
                {'2Y9G', 2347,147, 'DIYIPPEGLYFRLLGFASRQVIFARNSPSPDVGLSPVNDQATDQYFSLIYGTGEHAGLYAIKSKATGKVLFSRRPAEPYVGQIDGDGRYPDNWFKIEPGKTYLSKYFRLVQPSTGTALVSRTHLQPYFWNHPQTEVFDDQYFTFLFE'}
                {'2FL4', 2375,147, 'GMEIHFEKVTSDNRKAVENLQVFAEQQAFIESMAENLKESDQFPEWESAGIYDGNQLIGYAMYGRWQDGRVWLDRFLIDQRFQGQGYGKAACRLLMLKLIEKYQTNKLYLSVYDTNSSAIRLYQQLGFVFNGELDTNGERVMEWTHQ'}
                {'1J9E', 2135,147, 'AKALIVYGSTTGNTEYTAETIARELADAGYEVDCRDAASVEAGGLFEGFDLVLLGCSTWGDDSIELQDDFIPLFDSLEETGAQGRKVACFGCGDSSYEYFCGAVDAIEEKLKNLGAEIVQDGLRIDGDPRAARDDIVGWAHDVRGAI'}
                {'3HGM', 2261,147, 'MFNRIMVPVDGSKGAVKALEKGVGLQQLTGAELYILCVFKHHSLLEASLSMARPEQLDIPDDALKDYATEIAVQAKTRATELGVPADKVRAFVKGGRPSRTIVRFARKRECDLVVIGAQGTNGDKSLLLGSVAQRVAGSAHCPVLVV'}
                {'3S02', 2359,146, 'SVLEQIDQGSILKLPSNLLFENATSDAINQDMMLYIERIAKIIQKLPKRVHINVRGFTDDTPLVKTRFKSHYELAANRAYRVMKVLIQYGVNPNQLSFSSYGSTNPIAPNDSLENRMKNNRVEIFFSTDANDLSKIHSILDNEFNP'}
                {'4E8O', 2340,147, 'GMNIMPISESQLSDWLALRCLLWPDHEDVHLQEMRQLITQAHRLQLLAYTDTQQAIAMLEASIRYEYVNGTQTSPVAFLEGIFVLPEYRRSGIATGLVQQVEIWAKQFACTEFASDAALDNQISHAMHQALGFHETERVVYFKKNIG'}
                {'3NBC', 2221,148, 'SITPGTYNITNVAYTNRLIDLTGSNPAENTLIIGHHLNKTPSGYGNQQWTLVQLPHTTIYTMQAVNPQSYVRVRDDNLVDGAALVGSQQPTPVSIESAGNSGQFRIKIPNLGLALTLPSDANSTPIVLGEVDETSTNQLWAFESVSAV'}
                {'3MBT', 2380,149, 'GVTVVNNFDAKRYLGTWYEIARFDHRFERGLEKVTATYSLRDDGGLNVINKGYNPDRGMWQQSEGKAYFTGAPTRAALKVSFFGPFYGGYNVIALDREYRHALVSGPDRDYLWILSRTPTISDEVKQEMLAVATREGFDVSKFIWVQQP'}
                {'1GU1', 2223,149, 'RSLANAPIMILNGPNLNLLGQRQPEIYGSDTLADVEALCVKAAAAHGGTVDFRQSNHEGELVDWIHEARLNHCGIVINPAAYSHTSVAILDALNTCDGLPVVEVHISNIHQREPFRHHSYVSQRADGVVAGCGVQGYVFGVERIAALAG'}
                {'3AXC', 2423,149, 'MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGGMQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRL'}
                {'2Y9F', 2378,149, 'MTDIYIPPEGLYFRLLGFASRQVIFARNSPSPDVGLSPVNDQATDQYFSLIYGTGEHAGLYAIKSKATGKVLFSRRPAEPYVGQIDGDGRYPDNWFKIEPGKTYLSKYFRLVQPSTGTALVSRTHLQPYFWNHPQTEVFDDQYFTFLFE'}
                ];
end
*/
