@echo off
rem
rem
rem  #############################################################
rem  ##                                                         ##
rem  ##  compile.make  --  compile each of the TINKER routines  ##
rem  ##           (Intel Fortran for Windows Version)           ##
rem  ##                                                         ##
rem  #############################################################
rem
rem
rem  compile all the modules; "sizes" must be first since it is used
rem  to set static array dimensions in many of the other modules
rem
rem
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sizes.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\action.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\align.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\analyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\angang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\angbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\angpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\angtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\argue.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ascii.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\atmlst.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\atomid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\atoms.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bath.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bitor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bndpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bndstr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bound.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\boxes.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\cell.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\charge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\chgpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\chrono.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\chunks.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\couple.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\deriv.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\dipole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\disgeo.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\dma.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\domega.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\energi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ewald.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\faces.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\fft.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\fields.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\files.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\fracs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\freeze.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\gkstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\group.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\hescut.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\hessn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\hpmf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\improp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\imptor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\inform.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\inter.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\iounit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kanang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kangs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kantor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\katoms.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kbonds.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kchrge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kdipol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\keys.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\khbond.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kiprop.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kmulti.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kopbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kopdst.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\korbs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kpitor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kpolr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kstbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ksttor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ktorsn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ktrtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kurybr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kvdwpr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kvdws.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\light.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\limits.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\linmin.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\math.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mdstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\merck.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\minima.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\molcul.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\moldyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\moment.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mplpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mutant.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\neigh.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nonpol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nucleo.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\omega.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\opbend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\opdist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\openmp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\orbits.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\output.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\params.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\paths.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pbstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\phipsi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\piorbs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pistuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pme.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\polar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\polgrp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\polpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\potent.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\potfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\precis.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ptable.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\qmstuf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\refer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\resdue.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\restrn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rgddyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ring.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rotbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rxnfld.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rxnpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\scales.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sequen.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\shunt.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\socket.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\solute.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\stodyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\strbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\strtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\syntrn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\tarray.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\titles.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\torpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\tors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\tortor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\tree.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\units.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\uprior.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\urey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\urypot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\usage.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\usolve.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\valfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\vdw.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\vdwpot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\vibs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\virial.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\warp.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xtals.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\zclose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\zcoord.f
rem
rem  now compile separately each of the Fortran source files
rem
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\active.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\alchemy.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\analysis.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\analyze.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\angles.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\anneal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\archive.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\attach.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\basefile.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\beeman.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bicubic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bonds.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\born.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bounds.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\bussi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\calendar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\center.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\chkpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\chkring.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\chkxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\cholesky.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\clock.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\cluster.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\column.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\command.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\connect.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\connolly.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\control.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\correlate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\crystal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\cspline.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\cutoffs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\deflate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\delete.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\diagq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\diffeq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\diffuse.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\distgeom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\document.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\dynamic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangang1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangang2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangang3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangle1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangle2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangle3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangtor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangtor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eangtor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebond.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebond1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebond2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebond3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebuck.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebuck1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebuck2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ebuck3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echarge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echarge1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echarge2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echarge3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echgdpl.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echgdpl1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echgdpl2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\echgdpl3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\edipole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\edipole1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\edipole2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\edipole3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egauss.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egauss1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egauss2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egauss3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egeom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egeom1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egeom2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\egeom3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ehal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ehal1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ehal2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ehal3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimprop.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimprop1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimprop2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimprop3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimptor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimptor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimptor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eimptor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\elj.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\elj1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\elj2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\elj3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\embed.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emetal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emetal1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emetal2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emetal3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emm3hb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emm3hb1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emm3hb2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\emm3hb3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\empole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\empole1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\empole2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\empole3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\energy.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopbend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopbend1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopbend2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopbend3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopdist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopdist1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopdist2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eopdist3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\epitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\epitors1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\epitors2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\epitors3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\erf.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\erxnfld.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\erxnfld1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\erxnfld2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\erxnfld3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\esolv.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\esolv1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\esolv2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\esolv3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrbnd1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrbnd2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrbnd3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrtor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrtor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\estrtor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etors1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etors2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etors3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etortor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etortor1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etortor2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\etortor3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eurey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eurey1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eurey2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\eurey3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\evcorr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\extra.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\extra1.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\extra2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\extra3.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\fatal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\fft3d.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\fftpack.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\field.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\final.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\flatten.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\freeunit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\gda.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\geometry.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getkey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getmol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getmol2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getnumb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getref.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getstring.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\gettext.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getword.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\getxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ghmcstep.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\gradient.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\gradrgd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\gradrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\groups.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\grpline.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\gyrate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\hessian.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\hessrgd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\hessrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\hybrid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\image.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\impose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\induce.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\inertia.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\initatom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\initial.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\initprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\initres.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\initrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\insert.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\intedit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\intxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\invbeta.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\invert.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\jacobi.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kangang.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kangle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kangtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\katom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kbond.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kcharge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kdipole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kewald.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kextra.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kgeom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kimprop.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kimptor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kinetic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kmetal.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kmpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kopbend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kopdist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\korbit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kpitors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kpolar.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ksolv.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kstrbnd.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kstrtor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ktors.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ktortor.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kurey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\kvdw.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\lattice.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\lbfgs.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\lights.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\makeint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\makeref.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\makexyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\maxwell.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mdinit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mdrest.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mdsave.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mdstat.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mechanic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\merge.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\minimize.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\minirot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\minrigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\molecule.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\molxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\moments.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\monte.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\mutate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nblist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\newton.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\newtrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nextarg.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nexttext.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nspline.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\nucleic.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\number.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\numeral.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\numgrad.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\ocvm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\openend.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\optimize.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\optirot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\optrigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\optsave.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\orbital.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\orient.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\orthog.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\overlap.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\path.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pdbxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\picalc.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pmestuff.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pmpb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\polarize.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\poledit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\polymer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\potential.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\precise.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pressure.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prmedit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prmkey.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\promo.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\protein.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prtdyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prterr.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prtint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prtmol2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prtpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prtprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prtseq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\prtxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pss.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pssrigid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\pssrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\qrfact.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\quatfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\radial.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\random.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rattle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readdyn.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readgau.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readmol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readmol2.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readprm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readseq.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\readxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\replica.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\respa.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rgdstep.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rings.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rmsfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rotlist.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\rotpole.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\saddle.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\scan.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sdstep.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\search.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\server.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\shakeup.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sigmoid.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sktstuff.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sniffer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sort.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\spacefill.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\spectrum.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\square.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\suffix.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\superpose.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\surface.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\surfatom.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\switch.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\sybylxyz.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\temper.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\testgrad.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\testhess.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\testpair.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\testpol.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\testrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\timer.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\timerot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\tncg.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\torphase.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\torque.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\torsfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\torsions.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\trimtext.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\unitcell.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\valence.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\verlet.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\version.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\vibbig.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\vibrate.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\vibrot.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\volume.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xtalfit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xtalmin.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xyzatm.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xyzedit.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xyzint.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xyzpdb.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\xyzsybyl.f
ifort /c /O3 /QxHost /Qip- /Qprec-div- /w /Qopenmp ..\..\source\zatom.f
